### ISSUE TITLE
Setting slider to current image

### ISSUE THREAD

**Issue by ThomasDaheim** [tkuther/piwigo-bootstrap-darkroom#1]
Hi Thomas,

thanks a lot four your code! I have managed to incorporate your slider back into my theme :-)

Now I have run into the following: Seems like you try to set the slider to the image with this

```
$(".slick-slider").slick('goTo', currentThumbnailIndex, true);
```

On my site that makes the thumb to be the first in the slider, see http://www.feuster.com/piwigo/picture?/8970/category/714-lissabon_2016. But I would like to have it centered. How could I do that?

I have tried the centerMode option but that doesn't seem to work with slidesToScroll. Any other ideas?

Thanks in advance,
Thomas

**Comment by tkuther** [comment]
Hi Thomas,

"centerMode: true" forces slidesToScroll to 1, no matter what you set it to in the options. See https://github.com/kenwheeler/slick/pull/659.

What I like most currently is "centerMode: true" together with "swipeToSlide: true", that way the buttons scroll only by 1, BUT you can use the mouse to drag along more than 1 slide.

**Comment by ThomasDaheim** [comment]
On my Windows-Box this leads to a behavior that at the end of a mouse-drag the slider moves back to center the left-most (when dragging to the left) thumb. When dragging to the right a few more thumbs are scrolled to the right afterwards. Not necessarily what I would want :-(

**Comment by tkuther** [comment]
I'll close this for now as it's not really theme related.
