### ISSUE TITLE
Image Preview is not working when Link thumbnail to PhotoSwipe slideshow is enabled

### ISSUE THREAD

**Issue by rools32** [tkuther/piwigo-bootstrap-darkroom#10]
When I enable **Link thumbnail to PhotoSwipe slideshow**, the plugin *"Image Preview"* is not working anymore.

The **click tap** event (template/index.tpl) seems to mess with **Image Preview** in some way.

**Comment by tkuther** [comment]
Does it work if you change line 302 in template/index.tpl from
```
$(this).off().on('click tap', function(event) {
```
to
```
$(this).off('click tap').on('click tap', function(event) {
```
?

It looks like imgPreview attaches mousemove/hover events, so above could help. Having both link to photoswipe AND imgPreview could cause some real mess on mobile devices though.

**Comment by rools32** [comment]
It works! Thanks. On Android, I do not have any problem.

And congratulations for your great theme!

**Comment by tkuther** [comment]
Great. Will be in next version.
