### ISSUE TITLE
Need to know how to relocate Copyright block

### ISSUE THREAD

**Issue by Ainz** [tkuther/piwigo-bootstrap-darkroom#101]
I see many questions about this theme in the Piwigo foums, and very few answers. Maybe because the author thinks all support should go via GitHub?

In any case I refer to this: http://piwigo.org/forum/viewtopic.php?id=28178

Since I am not familiar with bootstrap coding I need an answer to what seems to me a VERY simple question.

Thank you

**Comment by tkuther** [comment]
Uhm, you're using "Bootstrap Default". This is the issue tracker for "Bootstrap Darkroom".

**Comment by Ainz** [comment]
I use darkroom on another site..
Assumed the code was the same? https://gallery.conram.com/

**Comment by tkuther** [comment]
bootstrapdefault is the parent theme, but darkroom overrides the footer template file. So, no, it's not the same.
