### ISSUE TITLE
OSM Map sometimes not shown in right panel

### ISSUE THREAD

**Issue by Dwerrog** [tkuther/piwigo-bootstrap-darkroom#102]
Since several versions I have a problem with theme "Bootstrap Darkroom" (actual version 1.5.20) and plugin "piwigo-openstreetmap" (version 2.8.d).

If I activate the switch "Stelle 'Zeige in OpenStreetMap' dar" (in german) for the right panel, the OSM-map is shown in the gallery.
But if I deactivate this option, the OSM-map disappears ...

In prior versions of "Bootstrap Darkroom" this problem doesn't occur (but I don't know in which version this problem 1st occur...).

![grafik](https://user-images.githubusercontent.com/31980069/30468017-f8f93d32-99e8-11e7-8160-e4d558af085b.png)
![grafik](https://user-images.githubusercontent.com/31980069/30468026-037e045e-99e9-11e7-8d6f-6c87b6ae6c05.png)

**Comment by tkuther** [comment]
Fixed in e904034, thanks!
