### ISSUE TITLE
Search box colors almost no contrast

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#103]
Hi TK, one of the last updates changed the search box colors, or its css dunno, now its very difficult to read what is being typed if you use the dark theme.

![image](https://user-images.githubusercontent.com/25783916/31103662-869d1d20-a7ae-11e7-8b64-25c11a141a53.png)

**Comment by tkuther** [comment]
Hi @pablopeu , this custom CSS should fix it.
```
#navbar-menubar>#quicksearch input[type="text"] {
  color: inherit;
}
```

**Comment by pablopeu** [comment]
Thanks Thomas, far better, if I wanted to leave it as it was versions before, I mean the inside of seach box in white background what should I change?

**Comment by pablopeu** [comment]
Im back at this, there is an inconsistence, on desktop the search box background is dark and per your CSS fix the font is gray. But on mobile the background is white and the text is still gray so its barely visible. Is there CSS fix for this? 
Thanks as always!

**Comment by tkuther** [comment]
Hi,

yes, it needs to be wrapped in a media query, like:
```
@media (min-width: 768px) {
  #navbar-menubar>#quicksearch input[type="text"] {
    color: inherit;
  }
}
```

**Comment by pablopeu** [comment]
Hi Thomas, Im transitioning to a new server with better capabilities and Im
moving the gallery, so far it works great, some minor cosmetic issues, I
recall you told me how to customize the height of the menu, but I can't
find which file to modify and what is the modification, here are the
captures of the old site (still in production) and the new one that need
modification which is on latest version of BS Darkroom. can you help me?
Thanks

**Comment by pablopeu** [comment]
![site old](https://user-images.githubusercontent.com/25783916/34183861-b5477b04-e4fb-11e7-988f-1e9ab42bb351.png)
![site new](https://user-images.githubusercontent.com/25783916/34183862-b57060dc-e4fb-11e7-8c7a-f3ddd6355f45.png)

**Comment by tkuther** [comment]
Hi Pablo,

it's custom CSS
```
.navbar-main {
  min-height: 150px;
}
```
..something like that

**Comment by pablopeu** [comment]
Hi Thomas, tried that, if I put a large value you see clearly that the
navbar is taller, but if you put lower values, even 1, it does not reduce
as it happened in the 1.5 release, the one that was live on my site until
yesterday

**Comment by tkuther** [comment]
You asked how to make it taller, right? Making it smaller than the font line height + margins/paddings won't work, and also wouldn't make any sense. Or am I misunderstanding what you're trying to achieve?

**Comment by pablopeu** [comment]
smaller :)
check how it was before: https://github.com/tkuther/piwigo-bootstrap-darkroom/issues/103#issuecomment-352918829

**Comment by tkuther** [comment]
Oh, OK. The lower picture looks like it should look, IMHO at least.

Try using height instead of max-height, and maybe even !important. Or higher z-index on the logo.
