### ISSUE TITLE
Can't upgrade & more

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#104]
Hi TK

Tried the upgrade via the dashboard and it errors, uploaded via ftp and uncompressed in a new folder and when I activate and set it by default I get these errors, if I don't erase cookies it even has more errors:

`
Warning: filemtime(): stat failed for ./themes/bootstrap_darkroom/css//bootstrap.min.css in /www/docs/peu.net/public_html/cuchillos/include/template.class.php on line 1894

Warning: filemtime(): stat failed for ./themes/bootstrap_darkroom/components/photography-icons/css/PhotographyIcons.css in /www/docs/peu.net/public_html/cuchillos/include/template.class.php on line 1894`

**Comment by pablopeu** [comment]
BTW:
Piwigo 2.9.2
Operating system: Linux
PHP: 5.6.21 (Show info) [2017-10-13 16:39:52]
MySQL: 5.0.45-Max [2017-10-13 16:39:52]
Graphics Library: GD bundled (2.1.0 compatible)

**Comment by tkuther** [comment]
Hi Pablo,

unfortunately I can't really help with that. Looks like a server issue.
Do the files exist? Is the time correct on the server?

You could try completely removing the bootstrap_darkroom folder und upload it fresh, or uninstall and reinstall the theme.

**Comment by pablopeu** [comment]
I see, just in case, do you have the link for the previous build in case something goes wrong? 1.5.20

**Comment by tkuther** [comment]
Sure, they are all on PEM http://piwigo.org/ext/extension_view.php?eid=831

**Comment by tkuther** [comment]
PS: the config remains in the database when uninstalling, so it's not lost. Downgrading is possible, too. Just manually install the old version, go to the theme's admin section and save the config once (need to change something so it actually saves everything)

**Comment by Dwerrog** [comment]
If you go to https://pwgdemo.kuther.net/admin.php you will also see this "filemtime(): stat"-warning before redirection ...

**Comment by tkuther** [comment]
Ah, thanks. Now I understand it.
It's an upstream Piwigo bug, actually. That redirect doesn't wait for the init trigger to finish, but tries to load the template (the variables are missing, resulting in a broken path and therefore "stat failed")

I can add a workaround by falling back to the default style if it's unset, just for that redirect thingy
