### ISSUE TITLE
after upgrade from 1.5.x to 2.0.1 several issues

### ISSUE THREAD

**Issue by tessus** [tkuther/piwigo-bootstrap-darkroom#105]
Something is seriously off with this version. see my gallery [here](https://gallery.evermeet.cx)

- The gallery name and the header is now about 10 times bigger.
- The distance between the album name and the info is way too wide.
- When there's an album with sub-albums and pictures, the alignment is still wrong.

How can I revert to the old code? 

It is currently unusable. I believe it has to do with bootstrap 4.
I've noticed that one can't just replace bootstrap 3 with 4. On one of my web pages it screwed up everything and I had to revert to bootstrap 3.

**Comment by tessus** [comment]
I tried to downgrade to 1.5.20, but I get the following error:

```
Warning: filemtime(): stat failed for ./themes/bootstrap_darkroom/css/default/bootstrap.min.css in /data/projects/piwigo/include/template.class.php on line 1894 Warning: filemtime(): stat failed for ./themes/bootstrap_darkroom/components/photography-icons/css/PhotographyIcons.css in /data/projects/piwigo/include/template.class.php on line 1894
```

**Comment by tessus** [comment]
[Please see this image for an explanation.](https://evermeet.cx/pub/tmp/explanation.jpg)

**Comment by tkuther** [comment]
Looks quite normal. In Bootstrap 4, the font size, line heights, navbar paddings etc have been increased by default. The space in the card is simply the paddings between the card-body and the card-footer:
![bildschirmfoto 2017-10-14 um 08 46 17](https://user-images.githubusercontent.com/63717/31573433-3e48436c-b0bc-11e7-9579-3a950ab13189.png)

You can use custom CSS to make things more compact.
Maybe I'll add a "condensed" theme at some point.

**Comment by tessus** [comment]
Unfortunately I have no idea how to use custom CSS.

The problem is that even on a Retina display, I have to scroll down almost 1/3rd of the screen, even though there are only 4 (I say again: four!) albums on the main page. I mean this can't be intended, can it?

**Comment by tessus** [comment]
Oh, btw, I always thought that going back is an option, but apparently this doesn't work. So right now I'm stuck with 2.0.1 and IMO it looks off. The header should be 1-2cm max, but instead it is 1/3rd of the screen. Is there any way to change the top black part to look as it did before?

**Comment by tkuther** [comment]
I count 5 albums on your main page, obviously. And as you can see, I do not have to scroll.

![bildschirmfoto 2017-10-14 um 09 02 05](https://user-images.githubusercontent.com/63717/31573555-8da0173a-b0be-11e7-8f5a-46a9d17613aa.png)

You could disable the jumbotron in theme settings. Or disable the "x fotos in y sub albums thing" Or, sorry, use custom CSS to make things more compact.

It's as easy as going to Admin -> Themes -> BS Darkroom Configuration -> Custom CSS
```
.card-body {
  padding: 0.75rem 1.25rem;
}
```

**Comment by tkuther** [comment]
Going back does work, you maybe just need to delete compiled templates in Admin -> Tools.
And you _need_ to go to the theme's configuration, change your style, and save to get the old config back.

**Comment by tessus** [comment]
Yes, you are right. There are 5 albmuns. You know, it's 3:17 here in Toronto and it was a long night. ;-)

Thanks, I will try your custom CSS and also to go back following your steps. It's just that I don't need 1/3rd of the screen black with the same text as already right at the top. To be more precise, I only need the menu bar really.

Other than that, I love your theme.

**Comment by tkuther** [comment]
That black header is called "Jumbotron". You can disable it in theme settings, select page header style: disabled.

**Comment by tessus** [comment]
Thank you, I'll play around with it tomorrow. Have to get some shut-eye.

**Comment by tkuther** [comment]
In 2.0.2, the card display is a bit more compact. And for the plack head, as sid, just disable the jumbotron.
