### ISSUE TITLE
Problem with Plugin "Admin Tools"

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#106]
There is a problem with the "Admin Tools" Plugin.

By klicking Administration the content is visible, but the title of the gallery splits the design of the Admin Tools. It is not possible to choose Alben, Benutzer, etc.
![vollbildaufzeichnung 14 10 2017 213803 bmp](https://user-images.githubusercontent.com/30748040/31578762-0a32065a-b128-11e7-9fe9-944c7bb31087.jpg)

Same problem on the right side when Werkzeuge is clicked.
![vollbildaufzeichnung 14 10 2017 214049 bmp](https://user-images.githubusercontent.com/30748040/31578780-694b9930-b128-11e7-89bd-320b0df3d22b.jpg)

**Comment by tkuther** [comment]
Hmm, that’s a z-index issue and it fights with the sticky navbar, too.

Could you try adding CSS class fixed-bottom to its most outer div using developer tools?

**Comment by tkuther** [comment]
OK, fixed-bottom alone won't do it.

The easiest fix is adding custom CSS like:
```
#ato_header {
  z-index: 1050;
}
```
It does look a bit awkward with the other navbar when scrolling down, but at least it works.
