### ISSUE TITLE
Problem with Full width layout

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#107]
When using the Full width layout the dropdown-content extends beyond the screen

![vollbildaufzeichnung 14 10 2017 214420 bmp](https://user-images.githubusercontent.com/30748040/31578824-7eb087da-b129-11e7-841c-0025dd1e6cdd.jpg)

**Comment by tkuther** [comment]
Which browser is that?

**Comment by ClaudiaLev** [comment]
It´s Firefox 56.0 64 Bit

**Comment by tkuther** [comment]
Does it happen here, too? http://pwg29.kuther.net

**Comment by ClaudiaLev** [comment]
Das sieht gut aus:
![vollbildaufzeichnung 14 10 2017 225704 bmp](https://user-images.githubusercontent.com/30748040/31579271-1c969206-b133-11e7-9eb8-ebc27b5c27e8.jpg)

Liegt wohl daran, dass ich den Anmeldebereich ausgeblendet habe.
Der Dialog "Anmeldung" wird auf meiner Seite nicht angezeigt. Den habe ich über das Plugin Advanced Menue Manager ausgeblendet.

**Comment by ClaudiaLev** [comment]
Wenn ich das Plugin "Advanced Menue Manager" deaktiviere sieht es auch bei meiner Seite gut aus. Liegt also am Plugin.

**Comment by tkuther** [comment]
Ah OK, das Plugin ist leider gar nicht unterstützt. Lässt sich auch nicht so leicht ändern, weil es eine komplett andere HTML-Struktur erwartet..

**Comment by ClaudiaLev** [comment]
Dann werde ich das Plugin einfach ausgeschaltet lassen.

Habe schon den nächsten Fehler gefunden ... den melde ich aber erst, wenn ich ausschließen kann, dass ein Plugin stört. 

Danke für Deine Mühe!!

**Comment by tkuther** [comment]
Gerne! :-)

**Comment by ClaudiaLev** [comment]
Ich habe eben festgestellt, dass die Funktion zum Ausblenden von Menue-Überschriften ein fester Bestandteil von Piwigo 2.9.2 ist.
Einstellbar unter Konfiguration / Menue
Wenn man dort "Identifikation" auf ausblenden setzt, dann ist es die gleiche Problematik wie oben für das Plugin beschrieben. Das Dropdown-Menue ragt über den rechten Bildschirmrand hinaus.

**Comment by tkuther** [comment]
Guter Hinweis!

Das lässt sich beheben.
