### ISSUE TITLE
Album Description is displayed in the center and very large

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#108]
The album description is (always) displayed in the middle of the gallery-screen and very large

- Before the update the description was always left-aligned with the path specification.
Edit:
I just realized that this problem do not occurs on all albums. 
aligned left: https://www.die-weite-welt.de/index.php?/category/67
aligned center: https://www.die-weite-welt.de/index.php?/category/121

- Also, the font is displayed much larger than before.

Normal layout
![vollbildaufzeichnung 15 10 2017 010239 bmp](https://user-images.githubusercontent.com/30748040/31580100-8fc56942-b146-11e7-91e1-f59511893520.jpg)

Full width layout
![vollbildaufzeichnung 15 10 2017 010518 bmp](https://user-images.githubusercontent.com/30748040/31580067-abd20ee8-b145-11e7-85d9-98cbc5fed41c.jpg)

Another suggestion for the full width layout:
The photos should have a slightly larger distance to the side edge, like the writing in the navbar.

**Comment by ClaudiaLev** [comment]
Just for Information. I already changed the font-size under the pictures with CSS.
And I think the font in the navigationbar is to large as well.

Maybe it would be a good idea to make it possible for the User to change font-sizes in the theme-configuration.

**Comment by tkuther** [comment]
Hi,

in your aligned-center example you have 3 row of `<p>..</p>`
The aligned-left is just one row.

Actually they are both center aligned.

But admittedly, it does look weird because the whole flexbox is center aligned, while the text itself is left-aligned inside the box.

May I'll add two display options:
1) simple center-aligned, where the text is wrapped in an h5 heading like it is now
2) left-aligned for advanced descriptions

**Comment by ClaudiaLev** [comment]
Danke, dass Du das Problem so schnell aufgegriffen und scheinbar sogar schon eine Lösung für das nächste Update bereit hast.

**Comment by ClaudiaLev** [comment]
> in your aligned-center example you have 3 row of <p>..</p>
The aligned-left is just one row.

Ich verwende für die Erstellung der Beschreibungen das Plugin "FCK Editor"
Dort kann ich mir auch den Quelltext anzeigen lassen. 
Für mich als Laie sehen beide Enträge identisch aus. Auch bei der Seite, bei der die Beschreibung links dargestellt wird, werden mir im Quelltext drei Zeilen angezeigt.

https://www.die-weite-welt.de/index.php?/category/67

![vollbildaufzeichnung 15 10 2017 131222 bmp](https://user-images.githubusercontent.com/30748040/31584221-93f796fc-b1aa-11e7-894d-bec2c63bc0f2.jpg)

**Comment by ClaudiaLev** [comment]
Wenn ich im Custom CSS die Schriftgröße von H5 ändere:

.h5, h5 {
    font-size: 1rem;
}

dann wird der Text, der vorher linksbündig war, nun auch mittig angezeigt. 
Sorry, ich will nicht nerven, aber vielleicht hilft es ja ...

Sonnige Grüße aus Berlin
Claudia

**Comment by ClaudiaLev** [comment]
Danke für das schnelle Update!
Die Anzeigevariante "Erweitert" zerhackt jedoch leider die Texte.

Statt eines Zeilenumbruchs wird eine neue Spalte erzeugt und der Text erscheint wie in einer Tabelle.
Beispielseite: https://www.die-weite-welt.de/index.php?/category/5
![vollbildaufzeichnung 15 10 2017 183100 bmp](https://user-images.githubusercontent.com/30748040/31586844-6135c306-b1d7-11e7-91d8-26568fa7315c.jpg)

**Comment by tkuther** [comment]
Oops, die flexbox wieder. Ich korrigiere das im nächsten release

Als quick-fix hilft folgendes custom CSS
```
#content-description {
  display: block !important;
}
```

**Comment by ClaudiaLev** [comment]
Funktioniert!!
Danke!

Super Support!! :-)

**Comment by tkuther** [comment]
Super bug reports! (War ehrlich gemeint, ist schier unmöglich die ganzen Piwigo features und Einstellungsmöglichkeiten alle selbst durch zu testen. Da sind solche Hinweise echt hilfreich und ich habe auch keinerlei Skrupel 3 Updates in 3 Tagen raus zu schubbsen um das fix zu beheben ;-))

**Comment by ClaudiaLev** [comment]
Danke! Ich bin derzeit beruflich in einem Projekt bei dem ein neues Software-Release vor Einführung revisionssicher getestet werden muss ... ich schreibe die Testfälle ;-)

Ich habe noch weitere "Kleinigkeiten" entdeckt. Keine Funktionsmängel, sondern eher Design-Wünsche.
Habe etwas Skrupel wegen jeder Kleinigkeit "rumzumäkeln".
Wie ist es für Dich am besten? Für jede Sache sofort ein neues Issue aufmachen oder lieber sammeln?

**Comment by tkuther** [comment]
OK, ja Selenium-Tests für das Theme fehlen noch.. :D

Mach lieber für jeden ein extra Issue auf. Ist leichter zu tracken so.
