### ISSUE TITLE
Version 2.0.3 - Full Width Layout in Kombination mit GThumb+ - Design-Vorschlag 

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#109]
Das Plugin GThumb+ erzeugt bei der Bildübersicht etwas breitere Seitenränder als das Bootstrap-Darkroom-Thema, dadurch sind Text und Bilder nicht bündig (s. rote Markierung).

![vollbildaufzeichnung 15 10 2017 215612 bmp](https://user-images.githubusercontent.com/30748040/31588567-329a62b4-b1f4-11e7-85b0-a538916c0544.jpg)

Mein Wunsch/Vorsschlag wäre, dass die Seitenränder beim Bootstrap-Thema an die GThumb+-Ansicht  angepasst werden.

Außerdem empfinde ich den Abstand zwischen Beschreibung und Bildern zu groß. Er ist nach unten größer als nach oben (s. grüne Markierung)
Mir würde es besser gefallen, wenn der Abstand unten etwas schmaler wäre und dem Abstand oberhalb des Textes entsprechen würde.

**Comment by tkuther** [comment]
Hi,

das mit den Abständen oben lässt sich machen.

Beim Seitenabstand für GThumb+ wird es schwierig. Wenn du es dir in den developer tools des Browsers anschaust, siehst du, dass das `<ul id="thumbnails">` selbst kein padding/margin hat, sondern jedes Bild links und unten.

**Comment by ClaudiaLev** [comment]
Ach das hilft nicht viel wenn ich in die Developer Tools gucke, ich bin keine Programmiererin und mache alles per Trial & Error :-)

Als Laie dachte ich, dass man einfach beim Seitentitel, beim der Menuezeile und bei der Beschreibung den Seitenabstand rechts und links etwas breiter machen kann. 

Der Rand des Thumbnail-Bildergitters ist immer gleich breit, egal wie groß das Browserfenster ist.

**Comment by ClaudiaLev** [comment]
Ein (sehr) eigennütziger Vorschlag:
Davon ausgehen, dass die meisten User einen Abstand von 10 Pixel zwischen den Thumbnail wählen und das Design entsprechend anpassen ... *g*

**Comment by tkuther** [comment]
Hmmm... spiel mal damit:
```
ul#thumbnails {
  margin-left: -10px;
  margin-right: -10px;
}

```

**Comment by ClaudiaLev** [comment]
Jawollja! 
Das sieht gut aus!
