### ISSUE TITLE
Some Buttons not Working?

### ISSUE THREAD

**Issue by Maxmygsd** [tkuther/piwigo-bootstrap-darkroom#11]
Hey, please help me? I have the newest Bootstrap Darkroom theme installed in my Piwigo site but some buttons do nothing. On the advanced search clicking 'search' does nothing. Also, the login page (identification.php) the login button does not work however it does when I use the dropdown menu login option. 

I have checked other themes and it works on them, just not bootstrap.

Please help?

Thanks,
Steve

**Comment by tkuther** [comment]
Hi Steve,

I need a link to your gallery in order to check what goes wrong there. If your prefer that, you can send it via email to github <at> kuther.net.

**Comment by PeteLawrence** [comment]
Hi Thomas,

The URL is http://stock.originalcottages.co.uk.

We've noticed that the login fields and button on identification.php (which I believe this theme inherits from bootstrapdefault) aren't contained within a <form> tag.  Adding a form tag manually and setting the action to be /identification.php fixes the problem.

Pete

**Comment by tkuther** [comment]
@PeteLawrence great hint. That gets us closer.

But unfortunately, I still can't reproduce it. I do see on your page the form tags are missing, indeed. But on both of my installs they are there, e.g. https://pwgdemo.kuther.net/identification.php - the Demo is a pretty plain Piwigo install with just a few plugins.

Can you please check if it does work (or doesn't) with bootstrap default on your site?

**Comment by PeteLawrence** [comment]
Thanks for getting back to us so promptly.

I've switched the site to use bootstrapdefault and the problem remains.

Strangely, if I use curl to view the page source the form tags are present, but if I disable JS within Chrome or Safari the form tags are hidden, suggesting it's not any JS that's messing with the form.

I'll raise this issue at the bootstrapdefault project since it appears to be an upstream issue.

Thanks for your help,
Pete

**Comment by tkuther** [comment]
@PeteLawrence ok, thanks.

The only idea I have is trying to move the form tags inside the panel-body in bootstrapdefault/template/identification.tpl. Could you try that, please? You can copy the edited file to bootstrap_darkroom/template/ for testing.

**Comment by PeteLawrence** [comment]
@tkuther The change you suggested didn't fix the problem, however, in playing about I discovered that an extraneous </form> element has made its way into the markup (via the Page Banner setting) which was causing the browser to strip the subsequent form tags as they didn't balance.

Thanks for your assistance and sorry for wasting your time.
