### ISSUE TITLE
Version 2.0.3 - Anzeigeprobleme Apple iPad/iPhone mit Safari

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#110]
Bei iOS/Safari gibt es ein Anzeigeproblem. Getestet mit iPad und iPhone.

Die Galerie und die Album-Ansichten werden grundsätzlich erstmal richtig angezeigt. Klickt man sich "normal" durch die Seite, dann wird alles korrekt angezeigt.

Lädt man eine Seite jedoch manuell neu, dann werden die Album-Boxen nach unten vergrößert.
Der Fehler betrifft nur Seiten, auf denen Alben sind, die zusätzlich zum Album-Titel noch eine Beschreibung haben. Die Länge der Boxen wird nach dem aktualisieren scheinbar genau verdoppelt.

Normale Ansicht
![img_0334](https://user-images.githubusercontent.com/30748040/31590173-235b7852-b20c-11e7-8866-00ad964f6d88.PNG)

Ansicht nach dem Aktualisieren der Seite
![img_0335](https://user-images.githubusercontent.com/30748040/31590178-3d70b004-b20c-11e7-9aec-4287bc0a42c3.PNG)

Diese "falsche" Ansicht bleibt auch bestehen, wenn man nochmals manuell aktualisiert.
Lädt man die Seite erneut über den Link "Europa", dann wird wieder alles richtig angezeigt.

**Comment by tkuther** [comment]
Hmm, leider kann ich es auf keinem meiner iDevices nachstellen (iPhone, iPad Air jeweils mit iOS 11)...

**Comment by ClaudiaLev** [comment]
Ich habe es mit iPhone, iPadMini und iPadPro ausprobiert und der Effekt tritt bei allen auf.
Ich habe allerdings noch nicht iOS 11.

**Comment by tkuther** [comment]
Closing, weil iOS 10 ist ohnehin veraltet mittlerweile
