### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by hartundweich** [tkuther/piwigo-bootstrap-darkroom#111]
Hello,
the last working version for me is 1.5.20 - as starting with version 2.0.0 the gallery is not working as expexting. 
Look here at the screenshot - maybe you can tell me what is happening? See both screenshots - I'm expecting a result as shown in the screenshot version 1.5.20
![1 5 20_correct](https://user-images.githubusercontent.com/18597291/31600336-58cad13c-b256-11e7-9f82-2f1de753589b.png)
![2 0 3_wrong](https://user-images.githubusercontent.com/18597291/31600338-58ebda3a-b256-11e7-822e-26f99818973d.png)

**Comment by tkuther** [comment]
That looks weird. Please try deleting the compiled templates in Admin -> Tools -> remove compiled templates (zu Deutsch "Kompilierte Vorlagen entfernen")

**Comment by tkuther** [comment]
Nevermind, its a bug with that number of comments display. It's so deeply hidden in the user preferences, it took me 30 minutes to find it.

I'll fix this in next version. Thanks for reporting!

**Comment by hartundweich** [comment]
remove ccmpiled templates does not fix this issue, I have tried this before posting this issue. Actual commit is working - thank you for resolving this issue so quickly.

**Comment by tkuther** [comment]
Cool. Take care there is a follow up commit that fixes the logic once more: https://github.com/tkuther/piwigo-bootstrap-darkroom/commit/1853ba6c56cf21fea12072fb8b743c6e649fa4f5

**Comment by hartundweich** [comment]
Thank you - just patched my running system with the latest commit.
