### ISSUE TITLE
Version 2.0.3 - Anzeigeproblem der Foto-Detailseite 

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#112]
Deaktiviert man für die Foto-Detailseite das Slick Carousel, dann wird unter dem Foto eine "Leerfläche" angezeigt, die mehrere Seiten lang ist. 

Will man die Bild-Informationen oder den Footer sehen muss man sehr weit scrollen.

**Comment by ClaudiaLev** [comment]
Noch ein weiterer Hinweis zur Foto-Detailseite.

Das Slick Carousel stellt maximal 7 Vorschaubilder dar.
Bei größeren Bildschirmen entstehen zwischen den Thumbnails sehr große Abstände. 
Vielleicht kann man ja die Anzahl der angezeigbaren Thumbnails erhöhen, so dass bei höheren Auflösungen mehr als 7 Bilder angezeigt werden.

**Comment by tkuther** [comment]
Danke! Ist beides behoben.
