### ISSUE TITLE
2.0.4 - Fehlermeldung nach Update

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#113]
Hallo, habe gerade das Update auf die neue Version gemacht. 
Nun kommt auf jeder Seite eine Fehlermeldung:

Warning: filemtime(): stat failed for ./themes/bootstrap_darkroom/components/bootstrap/dist/js/bootstrap.min.js in /mnt/web116/d2/02/5213002/htdocs/piwigo/include/template.class.php on line 1894

**Comment by ClaudiaLev** [comment]
Sorry, für die schnelle Meldung, hat wohl an MEINER Änderung im Header gelegen. ERLEDIGT

**Comment by Dwerrog** [comment]
Diese Meldung kommt auch weiterhin. Z. B. mal die Seite https://pwgdemo.kuther.net/admin.php aufrufen, dann erscheint genau diese Meldung kurz vor der Weiterleitung ...

**Comment by tkuther** [comment]
Das ist ein andres Problem.

**Comment by ClaudiaLev** [comment]
Bei mir kam die Fehlermeldung durch eine Änderung im Header.
Ich habe einen Code für ein Cookie-Info-Popup eingefügt.
https://cookieconsent.insites.com/download/

Im Rahmen der Theme-Aktualisierung wurde wohl auch der Header aktualisiert, so dass meine veränderte Vorlage, die auf der Vorversion basierte,  zu dieser Fehlermeldung geführt hat.
Nachdem ich den personalisierten Header deaktiviert habe, ist die Fehlermeldung verschwunden.

Vielleicht könnte man ja so ein Cookie-Info-Popup grundsätzlich ins Theme integrieren, sonst muss man das bei jeder neuen Version immer wieder neu manuell einfügen.

Sowas wäre sicher für viele User interessant, es gibt kein Piwigo-Plugin dazu.

**Comment by tkuther** [comment]
Für solche Dinge eignet sich das PersoFooter plugin hervorragend.

**Comment by ClaudiaLev** [comment]
Danke für den Tipp, das probiere ich mal aus.
In den Anleitungen steht immer, dass man den Code in den Header einfügen soll. Wenn man das auch in den Footer integrieren kann, umso besser!
