### ISSUE TITLE
2.0.4 Anzeigegröße bei Vollbildansicht

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#114]
Seit dem Update werden die Alben-Boxen deutlich kleiner angezeigt als vorher.
Allerdings NUR in der Vollbildansicht. Verkleinere ich die Größe des Browserfensters minimal, wird es wie vorher angezeigt.

Vollbildansicht (1680x1050)
![vollbildaufzeichnung 17 10 2017 203541 bmp](https://user-images.githubusercontent.com/30748040/31682614-eed488d8-b37a-11e7-93bf-f09a12b02612.jpg)

Minimal verkleinertes Browserfenster
![vollbildaufzeichnung 17 10 2017 203550 bmp](https://user-images.githubusercontent.com/30748040/31682637-fc969e3e-b37a-11e7-92e2-cd55ca65d322.jpg)

**Comment by tkuther** [comment]
Ja, ab 1680px breite sind es nun 6 Spalten beim fluid layout. Das ist so gewollt.

**Comment by ClaudiaLev** [comment]
Ok, damit kann ich mich auch anfreunden.

**Comment by ClaudiaLev** [comment]
Wobei der Sprung von 4 auf 6 Spalten ja recht ordentlich ist.
Wäre eine Ansicht mit 5 Spalten nicht auch eine gute Lösung?

**Comment by tkuther** [comment]
5 fände ich auch gut, geht aber leider nicht weil das Kachel-System von Bootstrap auf 12 Spalten basiert, das ist nicht restlos durch 5 teilbar (wenn man alle gleich breit haben möchte). 6, 4, 3, 2, 1 geht.

**Comment by ClaudiaLev** [comment]
Hm ... schade ... 
Aber danke für die allseits schnelle Rückinfo!!

**Comment by ClaudiaLev** [comment]
So richtig gut sieht das nicht aus, speziell wenn man nur wenige Unterordner hat.
Dann werden zwei lange Spalten an den linken Rand geschoben und rechts herrscht die große Leere 
![vollbildaufzeichnung 17 10 2017 214417 bmp](https://user-images.githubusercontent.com/30748040/31685812-9e482032-b384-11e7-937d-7d7c97a168f7.jpg)


Das hat mir vorher besser gefallen.
Gibt es ggf. eine Möglichkeit diesen Sprung von 4 auf 6 Zeilen per CSS zu überschreiben und auf einen höheren Wert zu setzen?

**Comment by tkuther** [comment]
Das sieht in der Tat etwas traurig aus. Ich mache es optional..
