### ISSUE TITLE
Version 2.0.5 - Dropdown-Menue für Alben etwas zu kurz

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#115]
Hallo,
danke für das neue Update, das sieht nun richtig gut aus!!

Eine winzige Kleinigkeit ist mir aufgefallen:
Beim Dropdown-Menue Alben muss ich etwas scrollen, um die Summe der Fotos sehen zu können. 

![vollbildaufzeichnung 19 10 2017 002218 bmp](https://user-images.githubusercontent.com/30748040/31745934-20493248-b465-11e7-9601-709a9de65705.jpg)

Hier wäre nach unten ausreichend Platz um das Menue länger darzustellen, damit man nicht scrollen muss.  Das ist kein echter Fehler, ich kann auch gut mit der aktuellen Ansicht leben, aber ggf. kann man das ja ganz einfach korrigieren. 

Außerdem wäre weiterhin mein Vorschlag den Abstand zwischen Album-Beschreibung und Bildern etwas enger zu machen.

![vollbildaufzeichnung 19 10 2017 002256 bmp](https://user-images.githubusercontent.com/30748040/31746031-9aa51700-b465-11e7-99d4-da686b420043.jpg)

Viele Grüße
Claudia

**Comment by tkuther** [comment]
Das Thema mit dem Abstand sollte in der nächsten Version (2.0.8) auch behoben sein. Du kannst es gerne jetzt schon testen. Einfach die Datei template/index.tpl, Zeile 165
`<div id="content-description" class="py-3 ...`
ändern in
`<div id="content-description" class="pt-4 ...`
Besser?

**Comment by ClaudiaLev** [comment]
Das hat leider nicht geholfen.

**Comment by ClaudiaLev** [comment]
Ich habs nochmal verglichen. 
Die Änderung führt dazu, dass der Abstand zur Menueleiste über der Beschreibung größer wird.
Mein Wunsch wäre, dass sie unten kleiner wird. Also der Abstand zwischen Beschreibung und den Thumbnails.

**Comment by tkuther** [comment]
Ja, es ist nicht ganz so leicht, weil z.B. bei dir die `<p>`-Elemente in der Beschreibung selbst auch ein margin-bottom haben:
![screenshot_20171023_115131](https://user-images.githubusercontent.com/63717/31882907-8f46493e-b7e8-11e7-8f93-78d641aab3cb.png)

In dem Fall könnte sowas helfen:
```
#content-description p:last-of-type {
  margin-bottom: 0px;
}
```
Aber eine generische Lösung gibt es da leider nicht, zuviele Möglichkeiten was alles in der Description stehen könnte.

**Comment by ClaudiaLev** [comment]
Danke, das probiere ich mal aus.

Ansonsten habe ich auch schon folgendes probiert, das funktioniert im Prinzip auch:
`ul#thumbnails {
  margin-top: -10px;
}
`

Nur bei Alben, die gar keine Beschreibung haben, rutschen die Thumbnails dann direkt an die Menueleiste.

**Comment by ClaudiaLev** [comment]
Deine vorgeschlagene Lösung hat zum gewünschten Ergebnis geführt.
Danke!
