### ISSUE TITLE
Broken design in Internet Explorer

### ISSUE THREAD

**Issue by ghost** [tkuther/piwigo-bootstrap-darkroom#116]
The design in Internet Explorer is not 100% right.

When you open the site https://pwgdemo.kuther.net/picture/55-oly00941/category/3-flowers with Firefox or Chrome it looks like this:

![firefox](https://user-images.githubusercontent.com/32923799/31780756-f03c37fc-b4f6-11e7-8d54-d0f9eec16300.jpg)

And now the same site with Internet Explorer:

![ie](https://user-images.githubusercontent.com/32923799/31780762-f60b0f8c-b4f6-11e7-840d-e813e5984a4a.jpg)

**Comment by tkuther** [comment]
Yeah, please use fluid-width if IE matters for you, or use a sane browser. I just don't care enough to look into it. Pull requests accepted.

**Comment by tkuther** [comment]
I'm closing this because upstream bootstrap also doesn't really care. It does work fine width fluid-width, though.
