### ISSUE TITLE
Start slideshow from current picture

### ISSUE THREAD

**Issue by MarcinJanowski** [tkuther/piwigo-bootstrap-darkroom#117]
Hello, is possible to start slideshow fom current picture? For example, when I browsing pictures manual, without slideshow and after few pictures i want to start slideshow, slideshow begins from first poto in galery, no my current photo.

**Comment by tkuther** [comment]
Not currently, but that's something that could be implemented.
It does exactly that when starting the slideshow from the thumbnail page, though.

**Comment by idbartosz** [comment]
@tkuther 
I think this small change will match up @MarcinJanowski issue.
