### ISSUE TITLE
Compatybility with Embedded Videos

### ISSUE THREAD

**Issue by MarcinJanowski** [tkuther/piwigo-bootstrap-darkroom#118]
Now when i have aded videos from Youtube with Embedded Videos extension, in slideshow i can see only thumbnail, is possible to show code to play video from Youtube?

**Comment by tkuther** [comment]
No, sorry. Video in PhotoSwipe is really tricky, and I won't extend it beyond playing server-local html5 compatible video files. Not at this time.

**Comment by MarcinJanowski** [comment]
Ok, thanks for answer.
