### ISSUE TITLE
Album-Beschreibung in der Grid-Ansicht - Idee/Vorschlag/Wunsch

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#119]
![vollbildaufzeichnung 20 10 2017 203249 bmp](https://user-images.githubusercontent.com/30748040/31836579-200d51fc-b5d6-11e7-90b9-21ac1ddfb054.jpg)

Man kann die Einstellung, ob man die Album-Beschreibung auch in der Grid-Ansicht sehen möchte für die gesamte Galerie festlegen.

Ggf. ein sehr spezieller Wunsch, aber ich würde es begrüßen, wenn man diese Auswahl für jedes Album separat vornehmen könnte. 

Bei einigen Alben möchte ich durchaus eine kurze Beschreibung in der Grid-Ansicht anzeigen.
Hat ein Album eine längere Beschreibung, dann ist die Grid-Ansicht aber nicht sinnvoll. Insofern muss man sich derzeit entscheiden. Entweder Grid-Ansicht oder ausführliche Beschreibungen. Beides zusammen ist designmäßig nicht möglich.

Ich vermute, dass die Umsetzung dieser Idee eher kompliziert ist, aber vielleicht gibt es ja doch eine Möglichkeit diese Idee für eine zukünftige Version aufzugreifen. 

Viele Grüße

Claudia

**Comment by tkuther** [comment]
Du kannst einfach das Extended Description Plugin nehmen.
http://piwigo.org/ext/extension_view.php?eid=175

> - have a small description for albums
> - have full descriptions on an album page.

**Comment by ClaudiaLev** [comment]
Danke für die schnelle Rückmeldung, das Plugin kannte ich noch nicht. 
Werde ich ausprobieren!
