### ISSUE TITLE
Ability to not use Google Font css

### ISSUE THREAD

**Issue by inkhey** [tkuther/piwigo-bootstrap-darkroom#12]
I just discovered that this theme import css from google fonts website. 
It will be nice to have  an option to deactivate this external dependency  for both local use (computer with no internet access) and privacy reason.

I can manually solve this issue by removing the line in css file but that's not optimal for updates.

**Comment by Ilav1** [comment]
Hello,

I would also like to get rid of the google font download. Where can I find the css file with the mentioned line?

I would like to delete the line for privacy reasons.

The thread was created in 2016 and no one has responded :-(
