### ISSUE TITLE
Photo dimension menu

### ISSUE THREAD

**Issue by fabrix95** [tkuther/piwigo-bootstrap-darkroom#120]
Hi guys,

with new version I find some problems with photo dimension menu. For example in theme 'Bootswatch Yeti' it is unreadble due to color of text. In theme 'Material Blue' with full width layout part of the menu is outside the screen.

![cattura](https://user-images.githubusercontent.com/27883759/31849839-7768d098-b649-11e7-82b9-f894ea748c5d.PNG)

**Comment by tkuther** [comment]
Thanks for reporting! Both will be fixed in next version.
