### ISSUE TITLE
2.0.7 - Full width view - Listenansicht gestört

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#122]
Habe gerade die neue Version installiert.
Bei der Listenansicht werden nun die Fotos nicht richtig skaliert

![vollbildaufzeichnung 21 10 2017 193444 bmp](https://user-images.githubusercontent.com/30748040/31854311-02d94070-b697-11e7-8882-f6bce185ec7b.jpg)

**Comment by tkuther** [comment]
Mist. Ist in der nächsten Version wieder heile.
Also quick-fix die Datei template/mainpage_categories.tpl editieren und so in Zeile 22 beo `<a href="..." class="d-block ripple">` das d-block entfernen

**Comment by ClaudiaLev** [comment]
Danke, das hat das Problem gelöst.
