### ISSUE TITLE
list view issue in picture thumbnails page

### ISSUE THREAD

**Issue by zoruspointorg** [tkuther/piwigo-bootstrap-darkroom#123]
Hi,
The last update corrected the issue with list view and grid view in the categories page. Now it works.
There is still a problem when one selects "list view" on the categories mainpage and then clicks on one category (album). The pictures are displayed in list view and we cannot revert back to grid view unless we return to the categories page.
In the picture thumbnails page in list view we can't recognize images (due to the resizing) and we can't change the display sizes.
Or is it a problem with my piwigo ?
my galery, if you want to check the issue : https://zorus.org/gplusphoto

Thanks for your help and for this great theme !

**Comment by tkuther** [comment]
Daaamn I swear I tested it. Will fix this in next release. Thanks for reporting.

**Comment by tkuther** [comment]
Fixed in 0d1b1984eb9537464b2596698baa6ce1a61ce16f. And it will behave like the one on category pages now (i.e. show the caption in list view by default)
