### ISSUE TITLE
homepage does not show any albums

### ISSUE THREAD

**Issue by leonieke** [tkuther/piwigo-bootstrap-darkroom#124]
After the recent update, I noticed that the homepage does not show any albums anymore:
https://leonieke.eu/photos/piwigo/

Should I change any settings to get albums back again?
Thanks!

**Comment by tkuther** [comment]
It seems the gdThumb plugin throws errors. There are other javascript errors, too, which indicates something went wrong.

First, try to delete compiled templates in Admin -> Tools -> Maintenance

If that doesn't help, try to uninstall the theme, make sure the themes/bootstrap_darkroom folder is gone afterwards, and install the theme again. The configuration will not be lost when uninstalling (could be called a bug, or a feature..)

**Comment by leonieke** [comment]
Thanks! Purging the compiled template did the trick!
