### ISSUE TITLE
Remove header at picture site

### ISSUE THREAD

**Issue by Digidani** [tkuther/piwigo-bootstrap-darkroom#125]
Is it possible to remove the header from the picture site?

At homepage or the categories the header looks cool, but at picture site you have to scroll down for the image. After a click left/right for next/previous image the header is displayed - and you have to scroll down again. So It would be better to remove the header from this site.

**Comment by tkuther** [comment]
Which header?

**Comment by Digidani** [comment]
I try it in German:

Ich meine den Kopfbereich und das dortige Hintergrundbild. Wäre schön, wenn man in der einzelnen Bildansicht dieses Bild ausblenden kann.

**Comment by tkuther** [comment]
In Administration -> Configuration -> Options -> Tab: Display, uncheck "Menubar" at Picture details page section

**Comment by Digidani** [comment]
Menüleiste! Das hätte ich niemals mit dem Bild in Verbindung gebracht! Danke auch hier!

**Comment by tkuther** [comment]
Ja, es ist zwar dann auch die obere Navigationsleiste weg, aber das ist zu verschmerzen denke ich.
