### ISSUE TITLE
Fontsize of image description

### ISSUE THREAD

**Issue by Digidani** [tkuther/piwigo-bootstrap-darkroom#126]
Where can I change the fontsize of image description?

**Comment by tkuther** [comment]
Use custom CSS, like
```
#theImageComment h4 {
  font-size: 1.25rem;
}
```
(1.25rem basically makes it a h5, which will be the default in next version)

**Comment by Digidani** [comment]
Danke!

**Comment by tkuther** [comment]
Bitte! ;-)
