### ISSUE TITLE
Startpage carousel + link to Additional Page

### ISSUE THREAD

**Issue by StifflersMoM69** [tkuther/piwigo-bootstrap-darkroom#127]
Hi!

Before Updating the Bootstrap Template i was able to Link all Pictures on the Frontpage to an Additonal Page.
The Code was
`<a` href="index.php?/page/kategorien"><img class="img-responsive" src="' + src + '" height="' + dheight + '"></img></a></div>');`

But now it seems this has been completly changed. Can you please help me out?

Thanks

**Comment by tkuther** [comment]
That code is just an anchor link. Where did you put it, and more importantly: how?

**Comment by StifflersMoM69** [comment]
After this right behind

`          $('#last10items .carousel-inner').append('<div class="carousel-item active text-center" style="background-image: url(\'' + src + '\')">`

**Comment by tkuther** [comment]
Ah, the carousel example. Well, that's because that example now uses background images. You could use captions or try to make it work with linked images.

**Comment by StifflersMoM69** [comment]
Okay... Thanks for that information, but i guess i have no clue how to get this done ;)

**Comment by tkuther** [comment]
If updated the example on the demo and the wiki, it now shows a button link to the gallery instead of the current picture's filename.

I guess that's more useful.

**Comment by StifflersMoM69** [comment]
Awesome! Thank you!
