### ISSUE TITLE
Changer la taille du nom des albums

### ISSUE THREAD

**Issue by mica91130** [tkuther/piwigo-bootstrap-darkroom#128]
Bonjour,

Comme indiqué dans le titre. Est-il possible simplement de modifier la taille de caractère du nom des albums.

Merci.

---------------

Hello,

As stated in the title. Is it possible to simply change the character size of the album name.

Thank you.

**Comment by tkuther** [comment]
Sure, use custom CSS like
```
.card-thumbnail h5 {
  font-size: 1rem;
}
```
