### ISSUE TITLE
openstreetmaps plugin broken since 2.0.9

### ISSUE THREAD

**Issue by MASHtm** [tkuther/piwigo-bootstrap-darkroom#129]
I upgraded to 2.0.9 today and the maps from openstreetmaps plugin doesn't show up on the startpage anymore. The place is reserved in the layout, but no map. deactivating/activating the plugin didn't help.

The maps only show up on the image details page.

**Comment by MASHtm** [comment]
looks like an update issue. After activating/deactivating "Full width layout" the OSM map reappeared.

**Comment by MASHtm** [comment]
no, it's the "Thumbnail page display" setting. With "simple" it doesn't show up. With "Advanced" it works.

**Comment by tkuther** [comment]
Thanks! Fixed in next version.
