### ISSUE TITLE
Adding photos (by community) not readable

### ISSUE THREAD

**Issue by keydoff** [tkuther/piwigo-bootstrap-darkroom#13]
Hello,

  Using the community plugin to let non-admin upload photos, the menu choice is not readable.
Changing the color from #dbdbdb to #0000 made it much better but it would affect other parts.

**Comment by tkuther** [comment]
Unfortunately, there are various issues with that plugin (e.g. https://github.com/Philio/bootstrapdefault/issues/32).
I can't really test it because both the flash and html upload forms are totally broken here. So I don't see a sane way to support it in the theme.

**Comment by zoruspointorg** [comment]
i used this in local files editor / css 
(local/css/bootstrap_darkroom-rules.css)
```
button, input, optgroup, select, textarea {
    margin: 0;
    font: inherit;
    color: #3c3c3c;
```
