### ISSUE TITLE
Integration with "Tag Groups" extension

### ISSUE THREAD

**Issue by strixaluco** [tkuther/piwigo-bootstrap-darkroom#130]
Greetings.

We are interested in having your great theme integrated with "Tag Groups" extension (http://piwigo.org/ext/extension_view.php?eid=781).
Let's say there are tags as these: `country:USA`, `country:France`, `weather:sunny`, `weather:cloudy`. So the idea is to have a separate *Tags* menu next to *Albums* and *Discover*, which would contain tags structured by groups:
```
country
 France
 USA

weather
 cloudy
 sunny
```

Could you please tell how much would such integration cost?
Thanks.

**Comment by tkuther** [comment]
The plugin is supported already. For any feature requests in the plugin (separate menu entries etc) you‘d need to ask the plugin developers. The plugin needs to expose such a menu, it can‘t be done in the theme alone.

**Comment by strixaluco** [comment]
Thanks for explanation. But the theme would still have to be adapted, is that right?

**Comment by tkuther** [comment]
Yes, ideally the plugin provides a menubar_tag_groups.tpl template file which can be overridden in the theme.

**Comment by strixaluco** [comment]
Got it, thanks. Reading [discussion](https://github.com/plegall/piwigo-tag_groups/issues/2) on similar issue at Tag Groups' repo, I tried appending URL with `?display_mode=groups`, as was advised, and it works.
Could that be of any use for your theme?

**Comment by tkuther** [comment]
That issue is about the standard tags page under Discover -> Tags.

What you want is a separate (top-level) menu, that would be a new feature of the plugin.

**Comment by strixaluco** [comment]
I see. Thanks for your time, we'll try to get plugin adjusted first.
