### ISSUE TITLE
Problems on displaying the gallery with Safari 9

### ISSUE THREAD

**Issue by Dadanaut** [tkuther/piwigo-bootstrap-darkroom#132]
Hi there,

I’m having some problems with Safari. The pictures are all stacked.

Firefox and other browsers show everything correctly. What can I do to correct this?

![bildschirmfoto 2017-11-11 um 19 09 52](https://user-images.githubusercontent.com/25630222/32692247-a10bb9b6-c714-11e7-973d-1bffc5a6f671.png)

**Comment by tkuther** [comment]
Which version of Safari is that? Is that Mountain Lion? o.O

**Comment by Dadanaut** [comment]
Safari 9.1.3 on Mac OS 10.9.5 (Mavericks).

**Comment by tkuther** [comment]
Yeah, well, that one's unsupported by Apple since 09/2016. So in your own interest you should use a supported, recent browser.

**Comment by Dadanaut** [comment]
Ah ok. Simple as that ... thanks.

**Comment by tkuther** [comment]
Hehe yeah it may sound harsh, but if even the vendor (Apple) stopped supporting it, why should anyone else?
If Safari 9 support really matters, you could install the last 1.x version of bootstrap darkroom (which is based on bootstrap 3), or you could try using the gdThumb Piwigo plugin which replaces the grid view, maybe it works better with that one.

**Comment by Dadanaut** [comment]
No. It’s ok. I understand. I sure do.
