### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by maximusVII** [tkuther/piwigo-bootstrap-darkroom#134]
With the latest release, my custom background image seems to be broken. It is still showing up on the login page but is no longer visible in the gallery itself.

This is my custom css code (added to custom css on bootstrap darkroom config page):
```
body{
background: url("/images/background.jpeg") no-repeat center center fixed;
}
```
If I uncheck the box combine JS&css in the piwigo developer tool, it is fully working again.

Any idea what is interfering with my custom css code?

**Comment by tkuther** [comment]
Try purging compiled templates in Admin -> Tools -> Maintenance.

If that doesn't help, check with your browser's developer tools if your custom CSS is present on the body element. Also `background-color: none !important;` could help.

**Comment by maximusVII** [comment]
I purged all compiled templated and included `background-color: none !important;` in the body element but the background image is still not visible in the album and picture view and the background color is still grey.

With the firefox development tool I can see the following error message:

```
Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://domain.com/_data/combined/yfu059.js
Source-Map-Adresse: bootstrap.min.js.map;
```

**Comment by tkuther** [comment]
The source map error shouldn't have any impact on rendering. Though, I would expect a 404 instead of a json parse error.

Anyways, I couldn't reproduce it here. Setting a background image works just fine for all pages.

Did you check if the background-image CSS is there at all on album and picture pages?

**Comment by maximusVII** [comment]
I've just double checked it and the background-image issues only occurs in the album view. The image is visible on the login and picture page.

The CSS background-image tag is visible on all pages (album, picture, login).

**Comment by maximusVII** [comment]
I included the following code to the config.inc.php file, which deativates the combination of the js&css code. The background-image is working again.

`$conf['template_combine_files'] = false;`
