### ISSUE TITLE
not issue but layout option request

### ISSUE THREAD

**Issue by t-o-d-d** [tkuther/piwigo-bootstrap-darkroom#135]
This is a great theme so glad you've made it! Thanks. 

My desire is to be able to have the "Picture page display" be the "card grid below the image" but ideally would like to have the comment section come before/above the info card grid. this was my commenters wouldn't have to scroll so far down to reach the comment section.

I'd also prefer the comment section to be center aligned rather than right aligned, whether it's above or below the info cards.

I am guessing these tweaks could be made without too much trouble for someone who knows CSS, but I do not. Thanks for reading. Todd

**Comment by tkuther** [comment]
Currently it would require a lot of jQuery hackeria, or ceating a child-theme.

I will turn it into a floating flexbox column grid at some point

**Comment by t-o-d-d** [comment]
Thanks for the reply. One more question. Why does the Exif card grid not show aperture with the other basic exif info? It would be nice to have the option to include it so viewers don't have to click the show exif button to get the basic info.

**Comment by tkuther** [comment]
Showing the FNumber should work fine if using the exif_view plugin. Without exif_view it depends on if it's "ApertureFNumber" or just "FNumber". The latter works for all my past and current cameras.

**Comment by t-o-d-d** [comment]
Aha nailed it.. For some reason I don't recall, my Fnumber was set to  'COMPUTED;ApertureFNumber', in the localfiles editor. Changing to Fnumber got it displaying in the card. Thanks
