### ISSUE TITLE
导航栏不能正常显示

### ISSUE THREAD

**Issue by eing888** [tkuther/piwigo-bootstrap-darkroom#137]
请帮我看看，我安装主题后，导航栏不能正常显示
如图
<img>http://leiting.win/1.png

**Comment by tkuther** [comment]
English, please!

**Comment by eing888** [comment]
Please look for me. After I install the theme, the bar navigation can't be displayed properly. thank you!

**Comment by eing888** [comment]
please help me to look at this problem. The naviqation bar cannot be displayed normally.
this is the screenshot of this mistake.
<img>http://leiting.win/1.png</img>

**Comment by tkuther** [comment]
You are using an incompatible plugin, looks like RV Menu tree. See https://github.com/tkuther/piwigo-bootstrap-darkroom/wiki/Plugin-Support-Matrix

**Comment by eing888** [comment]
Thank you. The problem was solved successfully.
