### ISSUE TITLE
Override elements style with local config 

### ISSUE THREAD

**Issue by GuillaumeCyriaque** [tkuther/piwigo-bootstrap-darkroom#138]
Hi Thomas,
How can I override some elements with local config instead of css ?
Like this : https://github.com/tkuther/piwigo-bootstrap-darkroom/wiki/Override-the-Navbar-style-and-background
https://bootswatch.com/lux/ -> buttons outline, small 
I have tested myself and don’t succeed...
Thanks

**Comment by tkuther** [comment]
Hi Guillaume,

so you want to add btn-outline-* classes?

The local config thing is only for the navbar color scheme (http://getbootstrap.com/docs/4.0/components/navbar/#color-schemes)

Adding/removing CSS classes for anything else requires either jQuery or Piwigo template overrides.

**Comment by GuillaumeCyriaque** [comment]
Hi,
Yes, that's it.
Now, I know why it doesn't work. Than you ;-)
