### ISSUE TITLE
Menu is not displaying

### ISSUE THREAD

**Issue by deepucpta** [tkuther/piwigo-bootstrap-darkroom#139]
see my gallery
http://www.indscoop.com/gallery/

No menu is displaying even it's activated in admin area and status plugin also not working

**Comment by tkuther** [comment]
Check if the menus are hidden in Admin -> Configuration -> Menus.

Anyway, it's not a theme problem because the menus aren't just hidden or failing to display, but the required HTML code is completely missing, so Piwigo core didn't generate it in the first place.

**Comment by deepucpta** [comment]
menus are not hidden, it's working with other themes

**Comment by tkuther** [comment]
Try purging compiled templates

**Comment by deepucpta** [comment]
Tried, still no luck

**Comment by tkuther** [comment]
Hmm, no idea then.

**Comment by deepucpta** [comment]
I've re-uploaded template files and finally its working!
