### ISSUE TITLE
Picture alignment broken when album contains pictures and sub-albums and GThumb+ is enabled

### ISSUE THREAD

**Issue by keydoff** [tkuther/piwigo-bootstrap-darkroom#14]
Hello,

  I have one album that has one photo and 16 sub-albums.
The sub-albums are showing correctly but not the photo (it still says 1 next to the album name).
When I switch to bootstrap-default, the photo is shown.
Do you know if it's related to some parameters I put or it's a bug?

Thank you very much

**Comment by tkuther** [comment]
Hi,

do you use any plugins like GThumb+ or gdThumb that influence thumbnail display. Which devices are affected (mobile, desktop, all of them)?
There is a known issue with GThumb+ where the direct image thumbnails would drift into the offcanvas on the right. See http://piwigo.org/forum/viewtopic.php?pid=163485#p163485

**Comment by keydoff** [comment]
Hello,

  Thank you very much, deactivating GThumb+ made the photo reappear.
So, I guess that i need to wait till a solution will be found for this issue before enabling GThumb+ and bootstrap-darkroom together.

Best regards

**Comment by tkuther** [comment]
Yeah unfortunately GThumb+ causes a mixed bag of themes standard thumbnails for albums and the masonry picture thumbnails. It does work fine with the gdThumb plugin, though.

So, either the GThumb+ needs support for "super albums" (those that contain both pictures and sub-albums), or we need another jQuery-move-around hack in the theme. (which will still result in differently styled thumbnails (bootstrap grid vs. masonry)).

**Comment by keydoff** [comment]
Thank you, I put gdThumb for now, it doesn't have this issue, and answering my needs.
If you want to keep this issue opened till it's solved with GThumb+, it's up to you.

**Comment by tkuther** [comment]
Reopening, as there should be a fix for this at some point.

**Comment by tkuther** [comment]
This seems fixed in the master branch. At least, the issue doesn't occur anymore with Bootstrap 4...
