### ISSUE TITLE
Schriftgröße Albumname 

### ISSUE THREAD

**Issue by hoopi1983** [tkuther/piwigo-bootstrap-darkroom#141]
Frohe Weihnachten!

ich möchte die Schriftgröße der Albennamen kleiner haben. In der Albenübersicht wird der Name nicht vollständig angezeigt und mit "..." beendet. ![titel](https://user-images.githubusercontent.com/34859701/34356806-76d8dc8c-ea41-11e7-8066-ef7fe4d9fda3.jpg) 

Wo kann ich diese Einstellung vornehmen?

Das zweite Problem was ich habe ist, dass wenn ich mehr als 100 Alben auf einer Seite anlege, die Albenthumbnailübersicht nicht mehr geordnet zu sehen ist.
![titel2](https://user-images.githubusercontent.com/34859701/34356816-8282171a-ea41-11e7-9ca2-1515b26fc401.jpg)
Kleiner 100 = alles schön geordnet
größer gleich 100 = Großes Chaos!

Ich hoffe, dass mir jemand helfen kann.

Gruß
hoopi

**Comment by hoopi1983** [comment]
Kann mir keiner helfen?

**Comment by tkuther** [comment]
Hi @hoopi1983 

für die Schriftgröße kannst du custom CSS verwenden.
```
.card-thumbnail h5.card-title {
  font-size: 1.1rem;
}
```

Das andere Problem kann ich leider nicht nachstellen. Für sowas ist gdThumb + RV thumbnail scroller besser geeignet, oder halt pagination.
