### ISSUE TITLE
Image Header and menu not formatted correctly in Internet Explorer 11.

### ISSUE THREAD

**Issue by MattHoyland** [tkuther/piwigo-bootstrap-darkroom#142]
Hi, I have a photo gallery using this theme (v.2.1.1) and when using IE11 the image header centralises and you cannot see the menu options (see attachment 1).  If I resize the IE window then it will snap to formatting the header correctly and seeing the menu (see attachment 2).  It works fine in Edge and on my iPhone. I'd appreciate if this could be fixed as I really like this theme.  Thanks.

Regards,

Matt

![photogallery1](https://user-images.githubusercontent.com/34969089/34457207-d6e5846e-eda1-11e7-8ad6-37f7ebcc531f.JPG)
![photogallery2](https://user-images.githubusercontent.com/34969089/34457208-d6fc397a-eda1-11e7-8156-de14d1482cc2.JPG)

**Comment by tkuther** [comment]
Duplicates #116
