### ISSUE TITLE
How to use "Pre generate custom size derivatives" script

### ISSUE THREAD

**Issue by orestesgaolin** [tkuther/piwigo-bootstrap-darkroom#144]
I found an article in [Wiki](https://github.com/tkuther/piwigo-bootstrap-darkroom/wiki/Pre-generate-custom-size-derivatives) with a script  that is supposed to generate all the required derivatives.

I wonder how to use it - where should I paste this snippet in order to generate all the required thumbnails etc.? 

Sorry for my incompetence but I couldn't find the answer by myself.
Have a great day
Cheers!

**Comment by orestesgaolin** [comment]
The solution was to precede the script with following:

```php
add_event_handler('init', 'bm_gen_custom_derivatives_form');
```

**Comment by dhui** [comment]
I also had to add:
```php
add_event_handler('element_set_global_action', 'bm_gen_custom_derivatives_action');
```

**Comment by tkuther** [comment]
Fixed the missing event handlers in the Wiki. Better late than never o.O

**Comment by daniele-athome** [comment]
Hello! I've been trying this on latest Piwigo release, but the action in batch manager doesn't come up. Do I need to modify it to work with this version? Thanks!
