### ISSUE TITLE
Github repo doesn't match Piwigo extension:theme release

### ISSUE THREAD

**Issue by idbartosz** [tkuther/piwigo-bootstrap-darkroom#148]
piwigo-bootstrap-darkroom-2.2.0.zip (20110898 bytes) - **Github**
`SHA256: A5BFF4F60CA1E8991014471994AD767DD4DFF4D8DBDA32027320302685FBBEFA`

bootstrap_darkroom_2.2.0.zip (20160681 bytes) - **Piwigo**
`SHA256: 924397003F8B15753717F1FCC16750CD4910364540AC6322E4D1597E4C4D464B`

**Comment by tkuther** [comment]
Hi,

PEM pulls directly from master and maybe adds some stuff, so it’s not the same zip.

**Comment by idbartosz** [comment]
Ah, thanks for info 👍 Indeed they only diff with `obsolete.list` and `pem_metadata.txt`.
