### ISSUE TITLE
Mouse move resets slideshow timer, but keyboard doesn't

### ISSUE THREAD

**Issue by readonly24** [tkuther/piwigo-bootstrap-darkroom#149]
Hi,

in Photoswipe slideshow a mouse move resets the (4 seconds) timer for the controls, but if I use only keyboard (arrow keys) to scroll throught an album, the controls never come back to screen.

**Comment by tkuther** [comment]
This is on purpose. In fullscreen view you wouldn't want the controls to show up when toggling next/prev using arrow keys.

**Comment by readonly24** [comment]
Am 23.02.2018 um 09:05 schrieb Thomas Kuther:
> Closed #149 <https://github.com/tkuther/piwigo-bootstrap-darkroom/issues/149>.

Hallo Thomas,

wäre es denn möglich, dass zumindest der Name/Titel des Bildes angezeigt wird?

-- 
Timo

**Comment by readonly24** [comment]
Thomas, what do you think?

**Comment by tkuther** [comment]
There doesn’t seem to be a function in Photoswipe to explicitly show the caption, so I don’t think it’s possible.

**Comment by readonly24** [comment]
I changed opacity from 0 to 1 in bootstrap_darkroom/theme.css

.pswp__ui--idle .pswp__caption {
  opacity: 1;
}

This is exaclty what I was loooking for.
