### ISSUE TITLE
Numeric value of rating different than number of stars selected

### ISSUE THREAD

**Issue by orestesgaolin** [tkuther/piwigo-bootstrap-darkroom#150]
In our Piwigo gallery with Bootstrap Darkroom 2.2.0 the rating scale seems a little bit odd to us.

The numerical value of rating after clicking stars ⭐ seems to be almost quasi-random, different for different users and only slightly correlated to the number of stars. Please see the attached GIF (mouse cursor is not visible though).

![2018-02-17_19-19-03](https://user-images.githubusercontent.com/16854239/36344242-91d95a2a-1417-11e8-95c2-ecb51318fdb1.gif)

How do you think - is it something wrong with the Piwigo itself or the Bootstrap Darkroom theme? In Bootstrap Default there is no numerical value provided, but the star count agrees.

Environment details:

> Piwigo 2.9.2
> Operating system: Linux
> PHP: 7.1.13 [2018-02-17 18:23:42]
> MySQL: 5.6.39-log [2018-02-17 19:23:42]

**Comment by tkuther** [comment]
It seems to be a piwigo core "issue" in how it calculates the average.

**Comment by deheme** [comment]
Score is not calculated as an average since a while in Piwigo. Maybe this is the reason.
http://br.piwigo.org/releases/2.3.0#rating_score
Regards

**Comment by orestesgaolin** [comment]
@daheme thank you very much for the clarification and the link! This now seems much more justified.
