### ISSUE TITLE
Thumbnail orientation

### ISSUE THREAD

**Issue by dreamscape440** [tkuther/piwigo-bootstrap-darkroom#151]
Hi, firstly thanks for this great theme it is fantastic!

I've been looking for a way to change the thumbnail orientation as currently it shows the center of the image which in my case tends to show the mid area of a female which makes the gallery seem a little perverse... 

Is there any way to change this or if not could it possibly be added so i could set the thumbnails higher up so it shows the persons face not body.

Thanks again for all the great work!

**Comment by jradwan** [comment]
Hahaha ... I've had the same problem. I've been using the "Center of Interest" tab on the photo details to change the thumbnail, but agree it would be nice if this could be auto-set. I don't think this is necessarily a problem with the theme, but the Piwigo engine itself.

**Comment by dreamscape440** [comment]
Ah I see so it's Piwigo? 

I do recall I didn't have this issue with the previous theme i used (it's name escapes me now) so I assumed it was the theme. It's rather annoying especially when the person in question is in a bikini or something and the thumbnail is just endless chest area... It doesn't look good.

Would really appreciate a fix or work around if possible.

**Comment by tkuther** [comment]
Well, either use the “center of interest” feature (which picks the middle by default), or use a plugin like gthumb+ or gdthumb which requires less cropping.

Some AI for the center-of-interest feature so it automatically picks the faces would be cool though..

**Comment by ClaudiaLev** [comment]
I used the Center of Interest-Feature in the past, but it takes a lot of time to use it on every single photo. My solution is to use the GThumb+ Plugin ... and I think the gallery looks better than before.

**Comment by jradwan** [comment]
I think I dropped GThumb+ when I switched to this theme (from Grey Dragon). Maybe I need to revisit that.

**Comment by dreamscape440** [comment]
I'm trying GThumb+ for now... it helps so thanks for that. 

Not perfect though as it doesn't effect directory thumbnails/sub directory thumbnails only actual pictures and it does seem to load considerably slower. But better than before for sure.
