### ISSUE TITLE
Thumbnail problem when picture > 4000px

### ISSUE THREAD

**Issue by fredm13** [tkuther/piwigo-bootstrap-darkroom#152]
Hi all,
Piwigo 2.9.2 / bootstrap darkroom 2.2.0.
xampp PHP: 5.6.24 / MySQL: 5.5.5-10.1.16-MariaDB / GD bundled (2.1.0 compatible)

When adding pictures, thumbnails from pictures > 4000px large are not displayed (error icon)
But when i change the theme for another, as 'clear' or 'stripped & columns', thumbnails are ok.

Msg error on i.php for a thumbnail : 

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 18220 bytes) in C:\xampp\htdocs\piwigo\admin\include\image.class.php on line 709

In my php.ini : 
memory_limit = 1024M
max_filesize = 600M

What can i do ? Thanks

**Comment by tkuther** [comment]
It looks like your php.ini setting has no effect, and your memory limit is still 128M.
Did you restart httpd?
What does php info show? (Piwigo admininistration -> Tools -> Maintenance -> php "view info")

**Comment by fredm13** [comment]
Yes, apache server restarted.
php info : 
memory_limit Local value 128M | Master value 1024M
