### ISSUE TITLE
/ missing in breadcrumb (recent_cats)

### ISSUE THREAD

**Issue by deheme** [tkuther/piwigo-bootstrap-darkroom#153]
In the breadcrumb the  / is missing  for recent_cats link.
Cf : https://pwgdemo.kuther.net/index/recent_cats

**Comment by tkuther** [comment]
Yeah for some reason recent_cats doesn’t use a anchor link in $TITLE which confuses the level stripping function in the theme. No idea how to fix this yet

**Comment by jradwan** [comment]
You can put that into Bootstrap Darkroom's Custom CSS block as well, but it seems to add the slash on the home screen then too:

![image](https://user-images.githubusercontent.com/11047158/36918193-158eed6c-1e27-11e8-8548-07dfe10f9bea.png)

**Comment by tkuther** [comment]
I found a proper fix/workaround for this.

**Comment by idbartosz** [comment]
It should do the trick but IMHO href should be `index.php?/recent_cats`.

**Comment by tkuther** [comment]
Not true if SEO URLs is enabled (no php extension and no question marks in url).
I guess it just doesn't really matter, or does it?

**Comment by idbartosz** [comment]
@tkuther 
Have you tested it? For me https://pwgdemo.kuther.net/index.php?/recent_cats works fine. Anyway we could take base URL from home item and concat it with `/recent_cats`

For template cohesion we should care but it's your project 😉

**Comment by tkuther** [comment]
Yeah it does "work", but it should be https://pwgdemo.kuther.net/index/recent_cats  - that's the problem.
Constructing it from base url would yield the same issue, you need to take into account what the user has configured in local/config.inc.php or you will cause duplicates in search indexes - unfortunately Piwigo doesn't provide an easy method to get this done, or I'm not aware of any.
href="#" doesn't do any harm to indexing at least.

A proper fix would be to make the $TITLE stuff consistent in piwigo core. All other pages create a link to itself here, just recent_cats doesn't.

**Comment by idbartosz** [comment]
@tkuther 
My idea was to use a built in link generating function or database record with the correct URL. I agree that the patch should be in the Piwigo core.

**Comment by tkuther** [comment]
Err, I just found that built in function I guess... well, will be in next release then.

**Comment by idbartosz** [comment]
@tkuther 
I suspect `make_index_url`.

**Comment by tkuther** [comment]
Yup, that one. Thanks for "pushing" me, that's indeed a better solution now.

**Comment by idbartosz** [comment]
Hehe, at your service 😈

**Comment by deheme** [comment]
I have updated to 2.2.1, and there is something different but not so nice : http://galerie.deheme.com/index/recent_cats
I've purged compiled templates...
![capture](https://user-images.githubusercontent.com/36800420/36933878-88b1d52a-1ee0-11e8-8c4b-4e0fc54ffde6.JPG)

**Comment by deheme** [comment]
Sorry for being boring but I've also an issue with favorites : http://galerie.deheme.com/index/favorites

**Comment by tkuther** [comment]
Hmm, there is something fishy, I just don’t know what yet.

**Comment by idbartosz** [comment]
This will be fixed in next Piwigo release. Anyway it's probably due to multiline $title string.

**Comment by tkuther** [comment]
It has something to do with AdditionalPages as home page. I was able to reproduce it, will look into it.

**Comment by tkuther** [comment]
Should be fine now. Thanks @deheme for reporting
