### ISSUE TITLE
Darkroom will not install

### ISSUE THREAD

**Issue by dlgentle** [tkuther/piwigo-bootstrap-darkroom#154]
I could not get the new version to update, so I then removed the darkroom theme.  It still will not install and now I don't have the theme at all.  I can install other themes, including bootstrap default.  Let me know if there are derivative files that need to be deleted or if anyone else is having this issue.  Thanks, I love this theme.

**Comment by ClaudiaLev** [comment]
I think you have to install bootstrap default first before you can intall bootstrap darkroom.
It is not necessary to activate bootstraß default, but it has to be installed.

**Comment by ClaudiaLev** [comment]
Hm ... sorry, no idea.
Maybe tkuther can help here.

**Comment by dlgentle** [comment]
tkuther: If I do the manual.  Will it just show up in the control panel once I throw it up?  Is that just a local unzip and ftp type of thing?

**Comment by dlgentle** [comment]
SOLVED: tkuther, that was the issue, just too stinkin' big.  I did a manual install and it worked great!  Thanks for all your hard work on this great theme!
