### ISSUE TITLE
Ladezeit Probleme bei aktiviertem Slick-Carousel im Firefox

### ISSUE THREAD

**Issue by thewebi** [tkuther/piwigo-bootstrap-darkroom#155]
Hallo zusammem,

ich habe das Problem das wenn ich Slick-Carousel aktiviere die Seiten sehr lange brauchen zum laden.
Das Problem besteht aktuell wohl nur im Firefox, im Safari lädt es ohne Probleme.

Bekomme dann auch im Firefox diese Fehlermeldung.
<img width="411" alt="slick-carousel_error_firefox" src="https://user-images.githubusercontent.com/36964746/36857638-4e71e232-1d79-11e8-8950-c90a6048c199.png">

Gruß

**Comment by tkuther** [comment]
Hi,

wieviele Bilder sind in dem Album?

**Comment by thewebi** [comment]
Hallo,

im Schnitt 500 Bilder.
Aufgrund Deiner Nachfrage habe ich mal diverse Alben aufgerufen und mir das angeschaut mit dem Laden.
Werden etwa alle Bilder aus dem Album vorgeladen? Wenn ja, wie am besten Cachen?

Gruß

**Comment by ClaudiaLev** [comment]
Direkt nach dem Update auf Piwigo 2.9.3 hatte ich diese Anzeige auch zweimal, allerdings nicht beim Slick-Carousel, sondern beim laden der Thumbnail-Übersicht. Inzwischen kommt die Fehlermeldung jedoch nicht mehr.

**Comment by tkuther** [comment]
Je nachdem, wie du es eingestellt hast in den theme settings bei den Slick Optionen -> lazy load Methode. "on demand" oder "progressive".

Progressive läd immer _alle_ Bilder, on demand nur die nächsten paar beim durch swipen.

**Comment by tkuther** [comment]
Ist das Problem noch aktuell?

Ich konnte es leider nie nachstellen, selbst bei einem Album mit 2k+ Bildern..

**Comment by thewebi** [comment]
Hat sich geklärt.
Liegt an den Bildern selbst, die sind einfach zu groß.

**Comment by thewebi** [comment]
Interesannt ist das ich das Problem auch nur im Firefox habe :(

**Comment by thewebi** [comment]
Also bei mir auf dem macbook funktioniert es im Safari ohne Probleme und im Firefox die oben genannte Meldung.

Habe es dann mal auf Arbeit im Firefox getestet unter Windows und dort bekomme ich meldung das ein Script blokiert aber zusätzlich will dort der Debuger starten.

Dort "meckert" er in der Datei xnoyi7.js Zeile 6 an.
Idee wie man das Problem lösen kann?
