### ISSUE TITLE
On image click run PhotoSwipe and/or sync images with Piwigo

### ISSUE THREAD

**Issue by idbartosz** [tkuther/piwigo-bootstrap-darkroom#156]
I'd like to ask users do they need such features? :bell: If yes I can do a PR.

### PhotoSwipe on image center click
![onclick](https://user-images.githubusercontent.com/21260478/36935365-5ea0824c-1ef7-11e8-99aa-421a53dc6b3d.gif)

### Sync PhotoSwipe slides with current Piwgo image
![sync](https://user-images.githubusercontent.com/21260478/36935372-691ffaf4-1ef7-11e8-8d08-ea650ae741f0.gif)

**Comment by tkuther** [comment]
The first one is available on mobile devices already (double tab).

The second one could be useful for some, but it should be configurable and disabled by default. And maybe asynchronous so swiping isn’t delayed.

Remember, this is a mobile first theme :)

**Comment by idbartosz** [comment]
Thanks for info about mobile tap.

Second feature could be async but it would require some sort API to get the crucial part. As you see now I'm doing a simple page reload. Now I consider adding at least image swap to make the reload less noticable.

**Comment by tkuther** [comment]
Ah, I thought you're going to constantly sync it on every change. So it would act more like a "shortcut" to pressing the "i" button in PhotoSwipe which does take you to the current picture's details page?

**Comment by idbartosz** [comment]
Indeed it works like 'i' triggered on close event. I'd like to make it async but it requires more work and time which I currently don't have :-)

IMHO constant reloads don't have sense when we got normal gallery browser right behind the scene.
