### ISSUE TITLE
Navbar on top?

### ISSUE THREAD

**Issue by helmut72** [tkuther/piwigo-bootstrap-darkroom#158]
Is it possible to have the navbar additionally on top (and bottom)? I don't use RV Thumb Scroller for some reasons and this "Plugin" doesn't work:
http://piwigo.org/doc/doku.php?id=dev:compilation_of_personal_plugins#add_a_top_navigation_bar

**Comment by tkuther** [comment]
By "navbar" you mean the pagination?
