### ISSUE TITLE
Inside categories images appear one below the other, menu items unresponsive

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#159]
Hi Thomas, if you browse my site www.peu.net on desktop you only see images next to the other on the main screen, but if you go to any category, they all appear one below the other.
On mobile it works as it should.
Also while inside a category, if you press any menu item, it doesn't respond, only from main page. Again, this works OK on mobile.

Thanks!

**Comment by tkuther** [comment]
Hi Pablo,

when I load a category, I first see what you describe, then after 2-3 seconds gdThumb plugin takes over and everything works as expected. It's just dog slow. I'd suggest reducing the number of pictures per page shown by default.

Also, don't use bootstrap_laguage_switch with Darkroom 2.x, it's not really compatible. The default language switch plugin shoud work fine.

**Comment by pablopeu** [comment]
Thanks Thomas, I temporarly disabled Cloudflare CDN and things run noticeable faster without touching anything, sorry for blaming BD :)

I mean waaaaay faster, I wonder what CDN stands for LMAO

Cheers
