### ISSUE TITLE
Video Icon in der Miniaturansicht

### ISSUE THREAD

**Issue by maximusVII** [tkuther/piwigo-bootstrap-darkroom#160]
Zuerst vielen Dank für das sensationelle Bootstrap Darkroom Thema!

Mir ist nicht ganz klar, ob mein Problem mit Piwigo oder dem Bootstrap Darkroom Thema zusammenhängt (oder mit einem anderen Plugin).

In meiner Bildergalerie haben ich Fotos und Videos. Bis vor kurzem hatten alle Videos in der Miniaturansicht ein Video-Icon oben rechts. Damit konnte man sehr gut Fotos und Videos auseinanderhalten. Das Icon ist nun leider plötzlich nicht mehr da.

Weiss jemand, wie sich dieses Icon wieder "aktivieren" lässt?

Vielen Dank für eure Hilfe

**Comment by tkuther** [comment]
Ups, das ging beim FontAwesome update verloren. Danke für den Hinweis.
