### ISSUE TITLE
Image resolution on high definition screen

### ISSUE THREAD

**Issue by fabrix95** [tkuther/piwigo-bootstrap-darkroom#161]
Hello,

I use Darkroom for my gallery but I notice that the image resolution is not so good using high definition screen (I think it depends from Piwigo core).

First of all, are there any chances to force automatic image size to "large" (or what else) for everyone and every screen?

Then (assuming "large" size 1008x672 selected), I noticed that I can obtain very nice photo resolution if I set width less then 1008 (i.e. 800 or 700): `<img src="..." width="800" alt="Photo" id="theMainImage" usemap="#maplarge">`

So I'd like to see image with 70/80% of original width to improve resolution. How can I do that? I'm trying using CSS without success...

I'd like to set default size to 1400px approximately and to display image at 1000px. 

Thank you in advance.

**Comment by tkuther** [comment]
You can set the default derivative size to large in local config with:
$conf['derivative_default_size'] = 'large';

I don't really understand the rest of your theory, though. Soft-scaling down the image via img width to 80% of the src file doesn't sound like a sane solution :-)
I don't see such issues with a 1080p and a retina 4k iMac. Maybe check your browser isn't set to 110% scaling or something?

Anyways, the template code uses the actual derivative's width for the img width, so CSS won't help here. You'd need to override the template and do the funky calculations there.

**Comment by fabrix95** [comment]
Thank you tkuther.

I set the default size.

About image resolution I've just tried Microsoft Edge and it works fine. 
Instead, Chrome and Firefox give not so good image resolution... they work fine with 80% of width. I don't know why, there's no zoom.

Anyway, thank you for info :)

**Comment by fabrix95** [comment]
I've just found the problem. Windows uses a rescaling factor (zoom of 125%) in order to display objets on relative small screen with hi resolution.

https://www.thurrott.com/windows/windows-10/4597/windows-10-feature-focus-display-scaling

So I think that the problem is for the most of windows users with laptop and high resolution :(

**Comment by fabrix95** [comment]
I've just found the problem. Windows uses a rescaling factor (zoom of 125%) in order to display objets on relative small screen with high resolution.
https://www.thurrott.com/windows/windows-10/4597/windows-10-feature-focus-display-scaling
So I think that the problem is for the most of windows users with laptop and high resolution :(

We should use window.devicePixelRatio to restore right image size.

https://www.jeffersonscher.com/res/resolution.php

![cattura](https://user-images.githubusercontent.com/27883759/39708178-c2d36962-5216-11e8-9a54-133669a282af.PNG)


Do you think that it's possible with template? Or should I ask to Piwigo forum?

**Comment by tkuther** [comment]
I’m not using Windows in any way, so I can’t test this. I don’t think it’s a Piwigo core issue either.
