### ISSUE TITLE
Source Map Error / Laden von gemischten Inhalten

### ISSUE THREAD

**Issue by ClaudiaLev** [tkuther/piwigo-bootstrap-darkroom#162]
Meine Webseiten laufen derzeit sehr gut mit dem Bootstrap Darkrook-Thema, und ich kann bei der Anzeige keine Probleme feststellen.

Guckt man sich die Webseite im Firefox mit "Element untersuchen" an und wechselt dann in die Ansicht "Konsole", dann erscheinen dort jedoch Fehlermeldungen/Hinweise.

Source Map Fehler:
![vollbildaufzeichnung 06 05 2018 130338 bmp](https://user-images.githubusercontent.com/30748040/39672672-fbbb0052-512e-11e8-9c79-20f8b85be472.jpg)

Bei meiner anderen Webseite, die mit https läuft erscheint ein Hinweis "Laden von gemischten Inhalten wurde blockiert" und auch der "Source Map Fehler"
![vollbildaufzeichnung 06 05 2018 130758 bmp](https://user-images.githubusercontent.com/30748040/39672673-ffae318e-512e-11e8-834e-5ed71c275d22.jpg)

Wie gesagt, ich kann eigentlich keine Probleme bei meinen Webseiten feststellen, wollte aber einfach mal darauf hinweisen, vielleicht sind sie ja für Programmierer interessant?

**Comment by tkuther** [comment]
Hi Claudia, der source map Fehler liegt daran, dass Piwigo die css files in eines zusammenfasst. Kann man ignorieren.

**Comment by tkuther** [comment]
PS: der gimschte Inhalt Fehler kommt von einer fehlerhaften SSL-Konfiguration.
