### ISSUE TITLE
Image thumbnails not available

### ISSUE THREAD

**Issue by jjambro** [tkuther/piwigo-bootstrap-darkroom#163]
I have been having an issue with thumbnails not displaying when I upload a larger image (over 1000px on the smallest side) unless I allow php to have more memory. Thumbnails that are generated and visible are of low quality compared with the original image (lots of jpeg artifacts). I'm using GD currently and not sure if I can move to ImageMagick with my current host.

I'd be fine with upping the php memory if the thumbnails looked better.

I'm not sure why 4 small square jpegs would swamp my php memory.

Your theme is my favorite I've used so far, and I'd hate to have to move to a different one

**Comment by tkuther** [comment]
You didn’t ask any question, but “... unless I allow php to have more memory” sounds like you answered the question you didn’t ask yourself. You didn’t say how much you needed to give it, I’d say 512MB sounds reasonable for larger jpegs. Image processing requires memory, give it as much as it needs.

**Comment by jjambro** [comment]
You're right, I guess I didn't ask a question.

Thanks for figuring out what I was trying to ask. :) From years of
Photoshop, I realize that image processing takes a lot of ram, I  didn't
think that just making a small jpg would be all that memory intensive.
