### ISSUE TITLE
Forward / backward for mp4 does not work on iPad

### ISSUE THREAD

**Issue by kuzco1** [tkuther/piwigo-bootstrap-darkroom#167]
Hello,
using latest piwigo 2.9.3 with latest Darkroom 2.3.2 theme.
Unfortunately I have some problems to play my *.mp4 on my iPad 2017.

Videos (1920x1080) are playing, but I am not able to forward or backward the video. I can do forward and backward, when switching into full-screen mode.
On my iPhone 8 I do not have these issues.

Any hint is welcome.

Regards
kuzco

**Comment by kuzco1** [comment]
Hello,
any news on that ?

Is there a way to downgrade the theme, so that I can check which version does not have this issue ?

Regards
kuzco

**Comment by tkuther** [comment]
Hmm, I can‘t reproduce this on my iPad Air...

**Comment by tkuther** [comment]
Old version can be found on PEM or here in the releases tab.

I don't know what you mean with 2. Link thumbnails to PhotoSwipe -> always?

**Comment by kuzco1** [comment]
Thnaks for tzhe info.
I have foind the old versions, but how can I install it. Just disable and delete the actual theme, and after that copy the "old" version in the theme-folder ?

Please ignore point 2 - have installed a backup and full-screen works now.
