### ISSUE TITLE
"undefined | Previous" links with RV Thumbnail Scroller

### ISSUE THREAD

**Issue by yurtseverfazli** [tkuther/piwigo-bootstrap-darkroom#169]
I keep thousands of photos in my albums on the adrres, www.medyastok.com. I use bootstrap darkroom. When you scroll down and see the link "see the remaining xx photos" and than click on the link the page refreshes and lists the remaining photos under a link "undefined | Previous". Here, if you click on "undefined" it produces Error 404. When I asked about this in piwigo forums, one of the members said 
"The error originates from RV Thumbnail Scroller plugin. Seems there's some incompatibility with the theme there.

Unfortunately I cannot reproduce it on any of my galleries, because none of my albums has enough images to trigger that "show remaining xx images" link. Too good culling, I guess.#

EDIT: that's the issue: [Github] piwigo-tscroller file rv_tscroller.js@L7
.navigationBar doesn't exist in darkroom"

The link for the issue in the forum "https://piwigo.org/forum/viewtopic.php?id=28758"

I am a newbee. I need your help to over come the problem.
Best regards.

**Comment by yurtseverfazli** [comment]
Problem still goes on! Any solution to be shared?

**Comment by tkuther** [comment]
That member on the forum is the author of the theme :-)

I‘ts an incompatibility that can‘t really be fixed in the theme, sorry.

**Comment by suiluj** [comment]
so is it possible to just delete the undefined text and link in the theme? it is really unnecessary.
