### ISSUE TITLE
Tabs not forced on mobile devices when using Sidebar for picture info

### ISSUE THREAD

**Issue by KrisGielen** [tkuther/piwigo-bootstrap-darkroom#17]
The configuration page states:
_Picture page display > Picture info display position > Note: on mobile devices the Tabs are forced, because the Sidebar button would overlay the main picture._
However, this is not happening. The picture info is simply not shown when selecting _Sidebar (like Bootstrap Default)_
I believe this is due to an slight error in _picture.tpl_
line 132:
``{if $theme_config_extra->picture_info == 'tabs' || (get_device() != 'desktop' && !$theme_config_extra->picture_info == 'disabled')}``
should be
``{if $theme_config_extra->picture_info == 'tabs' || (get_device() != 'desktop' && !($theme_config_extra->picture_info == 'disabled'))}``
and the same for line 145

**Comment by KrisGielen** [comment]
There's also a need to adapt lines 139 and 329.

**Comment by KrisGielen** [comment]
Just issued a Pull Request to solve this

**Comment by tkuther** [comment]
Good catch! Thanks.
