### ISSUE TITLE
When switching to Slovenian language page gets messed up

### ISSUE THREAD

**Issue by MarkoAmb** [tkuther/piwigo-bootstrap-darkroom#170]
When using bootstrap-darkroom in English, German, Croatian, Serbian, page is OK, but when switching to Slovenian language the page is messed up:
Take a look:
https://www.pc-help-ambrozic.com/fotogalerije/index.php?/category/79&lang=sl_SI

**Comment by tkuther** [comment]
You _need_ to leave en_GB enabled, because it's the base language (not en_US)
