### ISSUE TITLE
thumbnail captions

### ISSUE THREAD

**Issue by exekutive** [tkuther/piwigo-bootstrap-darkroom#175]
When thumbnail captions are turned on, the metadata name is shown, and if one doesn't exist, the filename is used instead. Is there a way to turn off filenames, so that if there is no metadata name/title, it will just show nothing?

**Comment by tkuther** [comment]
The template just uses `{$thumbnail.NAME}` variable it gets passed from core and there is no way to know if that name originates from metadata or the filename.
