### ISSUE TITLE
Button group does not wrap correctly

### ISSUE THREAD

**Issue by reisi007** [tkuther/piwigo-bootstrap-darkroom#178]
Hi,

How can I help you fix this bug? I fixed it in my installation using: 
`.btn-group {
flex-wrap: wrap
}`

I am not sure which is the perfect file to add this. Can you please either include it yourself or add instructions on where to add this code. I will create a PULL request!

**Comment by tkuther** [comment]
You could start with describing the problem.

**Comment by reisi007** [comment]
Hi,

(Answering per mail and trying to attach picture).

It is possible to browse pictures by creation date. The name of all months
currently is on one line, one has to scroll to the right to see all months.

As you can see in the image, which hopefully is attached, all months
starting from April would not be visible. The same is true for years of you
have enough years.

When wrapping is enabled everything works as expected. Note: This also
applies for desktop view.

Thanks for your answer, somehow I thought posting the solution to the
problem is enough!

Yours,

Florian

Am Sa., 10. Nov. 2018, 18:19 hat Thomas Kuther <notifications@github.com>
geschrieben:

**Comment by reisi007** [comment]
Hi,

(Answering per mail and trying to attach picture).

It is possible to browse pictures by creation date. The name of all months
currently is on one line, one has to scroll to the right to see all months.

As you can see in the image, which hopefully is attached, all months
starting from April would not be visible. The same is true for years of you
have enough years.

When wrapping is enabled everything works as expected. Note: This also
applies for desktop view.

Thanks for your answer, somehow I thought posting the solution to the
problem is enough!

Yours,

Florian

![screenshot_20181110-195534](https://user-images.githubusercontent.com/2719454/48304996-ab93b400-e523-11e8-8008-00e4f1074a26.png)

**Comment by tkuther** [comment]
Now I got it!

Thanks for the fix, it's in master now.

**Comment by reisi007** [comment]
@tkuther Thanks for integrating it so quickly! I will try to make before / after screenshots if I find anything in the future!
