### ISSUE TITLE
Pre generate custom size derivatives plugin won't resize images

### ISSUE THREAD

**Issue by skaldenhoven** [tkuther/piwigo-bootstrap-darkroom#184]
I wanted to pre generate the custom size images. I used the custom plugin provided in the wiki page but at first the option to generate these images wasn't even visible.
I found the issue #144 and tried the suggestions in there. The option became visible and I select e520x360  and I press apply but no images were generated. Also no error on screen / php logging.

I also tried putting it in a separate plugin config. (So created directory Custom_Derivatives and file main.inc.php with the contents from the wiki and added the add_event_handler) but still no luck.
Is there something that needs to be added/changed?

Environment:
Piwigo 2.9.4
OS: Linux
PHP: 7.0.32-0ubuntu0.16.04.1 (Toon info) [2018-12-14 09:51:26]
MySQL: 5.7.24-0ubuntu0.16.04.1 [2018-12-14 09:51:26]
Image Library: GD 2.1.1

**Comment by tkuther** [comment]
Sort of duplicates #144
