### ISSUE TITLE
Feature request: Option for showing search result on top because of TV Thumb Scroller

### ISSUE THREAD

**Issue by Schmidtze2** [tkuther/piwigo-bootstrap-darkroom#186]
When RV Thumb Scroller is activated and I do a search for example with "strand" then I see this

```
Albumresultate für strand
Malibu - Strand und bei Alex

Schlagwortergebnisse für strand
Strand
```
but at the end of the page. Or let's say I don't see it because when scrolling down, it will be shown for a very short moment, then it will disappear because of the RV Thumb Scroller new images will be loaded instead.

I changed index.tpl now for myself, so it will be shown on top. But an option would be great for this!!!

Best regards
Friedemann

**Comment by tkuther** [comment]
How do you get albums and tag results in the search?

I can only search for either albums, or tags/titles, but not both.

**Comment by Schmidtze2** [comment]
I'm using the quick search which is shown in the menu bar. Here you can see a screenshot which shows the result: https://www.dropbox.com/s/aavafdh63zfxjmn/26-12-_2018_12-03-00.png?dl=0

You really don't get such a result? I just checked my plugins but I didn't find one which causes this grouping. It's really cool! But as I said, normally it is shown below on the page...

**Comment by ClaudiaLev** [comment]
Ja, sieht bei mir auch so aus, aber nur wenn man die Schnellsuche direkt in der Menueleiste verwendet: 
![screenshot_2018-12-26 suchergebnisse](https://user-images.githubusercontent.com/30748040/50445948-59132900-0912-11e9-9b45-b75ac43250f4.png)

**Comment by tkuther** [comment]
Thanks, will look into it.
