### ISSUE TITLE
Feature request: Add Open Graph meta tags

### ISSUE THREAD

**Issue by reisi007** [tkuther/piwigo-bootstrap-darkroom#188]
[Open Graph metadata](http://ogp.me/) is used by Facebook & search engines to better detect the content of the page. I do not know if it makes more sense to have this on a theme or as a plugin, but I do not know how to get all the images / albums displayed on a page....

Just a honest question if including these meta tags, when displaying individual pictures or albums with subalbums would be a possibility.

**Comment by tkuther** [comment]
I think this better fits into a plugin.

**Comment by reisi007** [comment]
IMHO this is planned in future versions of Piwigo
