### ISSUE TITLE
using "local" CSS for Bootswatch

### ISSUE THREAD

**Issue by plegall** [tkuther/piwigo-bootstrap-darkroom#19]
Hi @tkuther 

Yesterday I have made some customization on a Piwigo with Bootstrap Darkroom and a Bootswatch theme. Very nice :-) But I couldn't use LocalFiles Editor to add CSS rules : they are loaded earlier than bootswatch CSS :-/

Instead of
`<link rel="stylesheet" type="text/css" href="https://bootswatch.com/{$theme_config_extra->bootswatch_theme}/bootstrap.min.css">`

we would need:

`{combine_css path="themes/bootstrap_darkroom/bootswatch/bootstrapp-{$theme_config_extra->bootswatch_theme}.css" order=?}`

So that LocalFiles Editor can work properly.

For now, I have added my specific CSS rules with plugin Perso Footer, but it's not what it was designed for ;-)

**Comment by tkuther** [comment]
Hi @plegall 

In the theme's config page is a custom CSS box that does work. This is from the parent bootstrapdefault theme, actually. There have been various reports on the forum that using LocalFilesEditor's custom css (and therefore the prefilter_local_css function from template.class.php) doesn't really work as expected with BootstrapDefault/Darkroom. No idea why.

But anyway, for consistency and offline joy, I added the bootswatch CSS files to the distribution and use combine_css.

**Comment by tkuther** [comment]
I had to revert this because it's more than just the CSS files. Needs web fonts and javascript, too.

Please just use the theme's custom CSS feature. It works with bootswatch.

**Comment by tkuther** [comment]
```
bower install bootswatch
```
.. so easy.

@plegall Please test if your modifications work now when using LocalFiles Editor.

**Comment by plegall** [comment]
Yes! now my local CSS are taken into account, that's perfect. Thank you @tkuther :-)
