### ISSUE TITLE
Comment icon: wrong link

### ISSUE THREAD

**Issue by mulanee** [tkuther/piwigo-bootstrap-darkroom#190]
Hi,

There is an issue in piwigo boostrap theme, the icons of the comments are reffering to a wrong link:

https://i0.wp.com/MYWEBSITE.COM/MYWEBSITE.COM/galerie/themes/bootstrap_darkroom/img/user.png?ssl=1

Changing a bit the link makes something happenning:
https://i0.wp.com/MYWEBSITE.COM/galerie/themes/bootstrap_darkroom/img/user.png?ssl=1

The difference is "MYWEBSITE.COM"

Please correct this or remove the icon.

**Comment by mulanee** [comment]
Thank you for the advise, I changed the absolute link to the relative one and it works now.

**Comment by tkuther** [comment]
OK. While it's sort of a valid bug report, I'll close this anyway as gallery_get_home_url() in core acts a bit unpredictable in such a case. So I think it's not a theme issue.

**Comment by Gr4ffy** [comment]
_Sorry, the parameters you provided were not valid_
https://i0.wp.com/gallery_url//themes/bootstrap_darkroom/img/user.png?ssl=1
