### ISSUE TITLE
Warning: filemtime(): stat failed on mobile devices

### ISSUE THREAD

**Issue by Schmidtze2** [tkuther/piwigo-bootstrap-darkroom#193]
After upgrading to 2.4.0 I get this warning now on bottom of the page:

```
Warning: filemtime(): stat failed for 
./themes/bootstrap_darkroom/js/jquery.mobile-events.min.js in 
/include/template.class.php on line 
1894
```
Maybe I can simply supress this warning, but I don't know where to set this up. But maybe it's an important information. On mobile devices the main burger menu icon now moves right out of the screen because of the long warning line on bottom of the page...

**Comment by Schmidtze2** [comment]
You can see it here: [https://fotos.friedemann.info/](https://fotos.friedemann.info)...

**Comment by tkuther** [comment]
Try purging compiled templates..

**Comment by Schmidtze2** [comment]
Oh, excuse me so much!!! I'm stupid, the warning says it exactly, the file jquery.mobile-events.min.js was mssing... I don't know how and why, but it seems I didn't copy it to the server... :-( So all runs finde now!!! Thanks!

**Comment by tkuther** [comment]
No, it got moved to node_modules/jQuery-Touch-Events/src/

Purging compiled templates should help (Administration -> Werkzeuge -> Wartung -> Kompilierte Vorlagen entfernen)

**Comment by Schmidtze2** [comment]
Oh no... excuse me again!!! I just reinstalled the theme from scratch, with the same result, the file jquery.mobile-events.min.js hasn't been found. BUT: Now I see, that I have a template-extension\bootstrap_darkroom\index.tpl in my installation, in which I moved up the search result section because of the plugin RV Thumb Scroller (see #186). Of course I didn't adjust this with the new location of the JS file. So the problem is fixed now! And please take a look again into #186 ;-)

**Comment by Schmidtze2** [comment]
A little bit strange and BTW; I had this problem only when using a mobile device. Using the dev tools in Chrome and switching to simulating a mobile device worked ok. I expected to see the same exception than on the real mobile devices...

**Comment by tkuther** [comment]
Could be browser caching, too.
