### ISSUE TITLE
Fatal error when empty galerie

### ISSUE THREAD

**Issue by philigrane** [tkuther/piwigo-bootstrap-darkroom#194]
When there is no gallery there is a fatal error. It is impossible to return to the administration to change the theme.
`Fatal error: Uncaught --> Smarty: Unable to load template file 'no_photo_yet.tpl' <-- thrown in /--------/include/smarty/libs/sysplugins/smarty_internal_template.php on line 139`

**Comment by tkuther** [comment]
Does themes/default/template/no_photo_yet.tpl exist in your installation?

**Comment by philigrane** [comment]
In default yes but not in bootstrap_darkroom

**Comment by philigrane** [comment]
Now i've this !?
```
Warning: include(/themeconf.inc.php): failed to open stream: No such file or directory in /----/include/template.class.php on line 1156

Warning: include(): Failed opening '/themeconf.inc.php' for inclusion (include_path='.:/opt/alt/php71/usr/share/pear') in /----/include/template.class.php on line 1156

Fatal error: Uncaught --> Smarty: Unable to load template file 'no_photo_yet.tpl' <-- thrown in /----/include/smarty/libs/sysplugins/smarty_internal_template.php on line 139
```

**Comment by tkuther** [comment]
Does your install work correctly with any other theme?

**Comment by philigrane** [comment]
Yes

**Comment by tkuther** [comment]
Hm, I couldn't reproduce this with a fresh install.

Sounds a lot like file permission fuckup.
