### ISSUE TITLE
Buttons and dropdown menus not working

### ISSUE THREAD

**Issue by JulPx** [tkuther/piwigo-bootstrap-darkroom#198]
Hi Bootstrap Darkroom community,

I experience problems accessing the buttons and dropdown menus on the website [https://photos.pidoux.me/](https://photos.pidoux.me/) with Bootstrap Darkroom latest version. I tried to delete and install the theme files again without success.

Has someone an idea to fix it ?

Thanks to the dev team for this great theme !

**Comment by tkuther** [comment]
PHP 7.3, right? https://github.com/Piwigo/Piwigo/issues/951

Unfortunately, this breaks darkroom.

**Comment by tkuther** [comment]
Duplicates #185

**Comment by JulPx** [comment]
> PHP 7.3, right? [Piwigo/Piwigo#951](https://github.com/Piwigo/Piwigo/issues/951)
> 
> Unfortunately, this breaks darkroom.

Hi @tkuther, thanks for your quick answer. I tried to delete Bootstrap darkroom and install it with PHP 7.2 running with no success.

**Comment by tkuther** [comment]
No need to uninstall. Did you try purging compiled templates?

**Comment by JulPx** [comment]
I did and the issue still remain.

**Comment by tkuther** [comment]
Well, no idea then. You definately had the jshrink deprecated warnings in the generated js file.

**Comment by JulPx** [comment]
@tkuther It's finally working with PHP 7.2, you were right. Thank you !
