### ISSUE TITLE
update from 2.3.5 to 2.4.1 messed up display on mobile

### ISSUE THREAD

**Issue by tessus** [tkuther/piwigo-bootstrap-darkroom#199]
I have a [gallery page](https://gallery.evermeet.cx/index/category/47) with 2 folders and 3 images.

However, the images are only shown in the desktop version. The mobile version only shows the 2 folders.

I've seen this problem before, but it has been finally fixed with one of the 2.3.x releases. Now it's back to not working. I really hope you can fix this somehow.

**Comment by tkuther** [comment]
Hm, you have smart pocket theme enabled and it's picked by default on mobile devices.
To view darkroom one needs to choose desktop view at bottom.

Anyways, both smart pocket and darkroom show both the albums and the images here on an elderly iPhone.

Which mobile theme are you talking about, and which device is it? (there are various threads on the forums stating smart pocket has issues on some Huawei mate phones)

**Comment by tessus** [comment]
> smart pocket theme enabled and it's picked by default on mobile devices.

This was not intentional. I have installed Darkroom a long time ago and thought it would be the default theme, since I set it as the default.
So it seems that it's really a `Smart Pocket` issue. Sorry for the noise then.

> Anyways, both smart pocket and darkroom show both the albums and the images here on an elderly iPhone.

I'm using a Google Pixel, Android Pie, and the latest version of Chrome for Android.
And you are right, I just tried on Samsung Galaxy S7 with Android 8 and latest Chrome and Smart Pocket seems to show the pictures there as well.
Very weird. Since when does rendering of HTML depend on the OS?

Darkroom works perfectly on my phone. I just didn't know that it was not Darkroom that was used.

> Which mobile theme are you talking about, and which device is it?

Apparently Smart Pocket. It does not seem to work on my Google Pixel. (It does not show images a all, only folders.)
Unfortunately the Piwigo team is not very reactive to any problem reports. The 3 times I had an issue, I never got help and in 2 cases no answer at all. So you can either live with a problem or switch the SW. In that case I will just deactivate their theme.

Thanks again and sorry for the ticket.

**Comment by tessus** [comment]
Oops, sorry. I clicked the wrong button. (I wanted to click `Close and comment`)
