### ISSUE TITLE
Category view: cannot navigate to other pages

### ISSUE THREAD

**Issue by pbernery** [tkuther/piwigo-bootstrap-darkroom#2]
Hello,

I just installed your theme which I love :).

I encounter a problem though: the page navigation bar does not display where there are more than 15 photos (this is the default value of Piwigo) in the category (or album) view.

The problem does not exist on the original [Boostrap Default theme](https://github.com/Philio/bootstrapdefault).

**Comment by tkuther** [comment]
Hi @pbernery,

args, sorry for the trouble. I tried to implement something that hides the pagination links in case the RV Thumb Scroller plugin is active, but that doesn't work as expected.

As a quick fix, please edit piwigo/themes/bootstrap_darkroom/template/index.tpl. Around line 215  replace
```
{if !empty($thumb_navbar) && !isset($rv_tscroller_enabled)}
    {include file='navigation_bar.tpl' fragment="content"|@get_extent:'navbar' navbar=$thumb_navbar}
{/if}
```
with
```
{if !empty($thumb_navbar)}
    {include file='navigation_bar.tpl' fragment="content"|@get_extent:'navbar' navbar=$thumb_navbar}
{/if}
```

Thanks for reporting! I'll upload a fixed version soon.

**Comment by tkuther** [comment]
Just uploaded a new version to piwigo.org/ext.

I hope it works now. If it doesn't, please re-open this issue.

**Comment by pbernery** [comment]
Wow, that's fast :)
I just tested the updated theme and it works great, thank you very much!

**Comment by tkuther** [comment]
Great. Thanks for the feedback!
