### ISSUE TITLE
Fullscreen display shows wrong size

### ISSUE THREAD

**Issue by NickNew** [tkuther/piwigo-bootstrap-darkroom#20]
Fullscreen display worked correctly at first. But then I tried to change the image size in album view (that is, where you see thumbnails of all the photos in the album). It's a little weird that you can change the sizes here to bigger sizes, and actually "optimal" doesn't even work correctly. Anyway, after I did this, "fullscreen display" of a photo shows a very small size.

**Comment by tkuther** [comment]
Could you please try to clear your browser cache?
If that doesn't help, attach some screenshots here, please

**Comment by NickNew** [comment]
Hello,
    
    Clearing the browser cache worked. But changing the image size for
    the "thumbnails" in an album brings the problem back. I guess we'll
    just avoid doing that. If you want to see it, you can try here:
    https://punch.dau.no
    
    Thanks
    
    
    On 2017-01-19 09:00, Thomas Kuther
      wrote:
    
    
      Could you please try to clear your browser cache?
        If that doesn't help, attach some screenshots here, please
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tkuther/piwigo-bootstrap-darkroom","title":"tkuther/piwigo-bootstrap-darkroom","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tkuther/piwigo-bootstrap-darkroom"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tkuther in #20: Could you please try to clear your browser cache?\r\nIf that doesn't help, attach some screenshots here, please\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/tkuther/piwigo-bootstrap-darkroom/issues/20#issuecomment-273798407"}}}
    
    
  



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by tkuther** [comment]
Thanks! I could reproduce it now. I have disabled that button for the album page on my private gallery, but honestly I have no idea anymore _how_ I did it or even where that button comes from. It's still there on pwgdemo.kuther.net, so I'll see if a fix is possible.

**Comment by tkuther** [comment]
That was a really stupid bug which must have been there from day 1. Thanks for reporting this, Nick. Fixed in next version.
