### ISSUE TITLE
PhotoSwipe / Photo comments & title are hiding if no mouse move

### ISSUE THREAD

**Issue by croulibri** [tkuther/piwigo-bootstrap-darkroom#200]
Hello,

Thanks for the work of this great theme for Piwigo!
I really enjoy it very much.

I use to add comments on photos (to explain the situation of the photo,...).
If I want to see these photo full screen with PhotoSwipe, then title and comments of the photo appear at first.
But iff the slideshow is automatic, or if I change photos with keyboard, then title&comments of the photo are autohiding at the same time with the control button of PhotoSwipe.
I need to move the mouse to make them visible again.

Would it be possible to let the comments visible during an automatic slideshow ?

Thanks in advance!

**Comment by tkuther** [comment]
You could try using a CSS override like
```
.pswp__ui--idle .pswp__caption {
    opacity: 100 !important;
}
```
which should make the caption permanent.
