### ISSUE TITLE
Carousel sliver in frontpage

### ISSUE THREAD

**Issue by levagabond** [tkuther/piwigo-bootstrap-darkroom#201]
Hi, 
I would like to put on my frontpage the carousel slider that you put in the wiki, but using images from an independent file.
Because I have some pictures of very poor quality.
Can you help me with the script based on your carousel?

Best regards

PS : I love your theme

**Comment by tkuther** [comment]
Hi,

please understand that the issue tracker here is not a support forum.

See https://getbootstrap.com/docs/4.3/components/carousel/ for help, that examples there use local images.
