### ISSUE TITLE
Problems with updates

### ISSUE THREAD

**Issue by cryogenster** [tkuther/piwigo-bootstrap-darkroom#203]
Hello,

After update and after a new install of the template I get the following errors:
Warning: filemtime(): stat failed for ./themes/bootstrap_darkroom/node_modules/font-awesome/web-fonts-with-css/css/fontawesome-all.min.css in /home/xxxxxxxxx/public_html/xxxxxxxx/include/template.class.php on line 1894

Warning: file_get_contents(./themes/bootstrap_darkroom/node_modules/font-awesome/web-fonts-with-css/css/fontawesome-all.min.css): failed to open stream: No such file or directory in /home/xxxxxxxxxxxx/public_html/xxxxxxxxx/include/template.class.php on line 1990

Some forum posts also escalated on piwigo forums: https://piwigo.org/forum/viewtopic.php?pid=173189

Your help is appreciated.

**Comment by cryogenster** [comment]
UPD: this happened after the last piwigo and template. The piwigo installed in folder on server with the url like: https://domainname.com/xxxxxxxx/
So as I can see it's a problem with a url compiling.. Any suggestions?

**Comment by Schmidtze2** [comment]
I just posted this in the mentioned topic:

> Do you maybe have a template copy in template-extension\bootstrap_darkroom, for example 
> "index.tpl"? This has to be adjusted too to the new folder structure... I had the same problem.

Best regards
Friedemann

**Comment by tkuther** [comment]
Good catch @Schmidtze2 

So, to summarize:
- make sure any custom template overrides are updated
- purge compiled template cache
- purge the browser cache
