### ISSUE TITLE
Bootstrap and User Collection display bug

### ISSUE THREAD

**Issue by TontonA** [tkuther/piwigo-bootstrap-darkroom#204]
Hello, 
I'm using bootstrap darkroom themes for my piwigo installtion, and I just installed the plugin user collection which is supposed to be compatible with this themes. 
Actually I think the support is incomplete. When I'm in the collections pages I should see some icons like delete the colletion, empty or sharing. Instead I have this 
![image](https://user-images.githubusercontent.com/49813735/56458182-ba5c7d80-6383-11e9-8a03-53b9174d929a.png)

Do you think it's possible to add the according icons with your template plugin_fixes_js.tpl ? 

Thanks
Best

**Comment by tkuther** [comment]
There is only one icon added by user collections. The star one.
<img width="424" alt="Bildschirmfoto 2019-04-22 um 10 22 14" src="https://user-images.githubusercontent.com/63717/56491350-8a7aba80-64e8-11e9-8e3f-7f916f2d2859.png">

Though, support for the button is a crappy hack, the real fix would be template support in the plugin.

**Comment by TontonA** [comment]
Yes this icon is added in an album page. But my picture was taken in a collection page. When you are going in a collection (like https://photo.mydomain.ndd/index.php?/collections/edit/7) there are four new icons : 

- Share form
- Mail form
- Clear the collection
- Delete the collection

But I would like to help providing a template in the plugins but I don't really know how to do it. If you can give me some clue I will try to create the template for the plugin. 
Thanks

**Comment by tkuther** [comment]
Ah, you are right. The collection page looks broken.

A proper template would require to make https://github.com/mistic100/Piwigo-User-Collections/blob/master/template/thumbnails_css_js.tpl overridable. See also https://github.com/mistic100/Piwigo-User-Collections/pull/10
