### ISSUE TITLE
Aperture value does not appear in photo swipe

### ISSUE THREAD

**Issue by igalanommatis** [tkuther/piwigo-bootstrap-darkroom#209]
Hello,
I observed that the aperture value does not appear in photo swipe. I set `bootstrap_darkroom_ps_exif_mapping` mapping as `'apperture' => 'FNumber'` with no luck.

After some digging, I discovered that `apperture` is displayed only if it has a string value that contains an integer or a fixed-point number, whereas 'FNumber' is actually expressed as a fraction (like '28/10' for an aperture of f/2.8).

I have no knowledge in PHP or other web technologies to fix the issue but a quick and dirty workaround that "works for me" are these lines, to be put in `themecontroller.php` after `get_exif_data` block but before the "optional replacements" one.

```
if (array_key_exists('apperture', $tpl_var['EXIF'])) {
        $tmp = explode("/", $tpl_var['EXIF']['apperture'], 2);
        $tpl_var['EXIF']['apperture'] = $tmp[0] / $tmp[1];
}
```

Piwigo 2.9.5, Bootstrap-darkroom 2.4.1, PHP 7.2

Regards,
--Ioannis

edit: Similarly, focal length is displayed as "200/1" for 200mm, but at least it gets displayed.

**Comment by tkuther** [comment]
It sounds like you're missing the exif_view plugin.

**Comment by igalanommatis** [comment]
Yes, this is true.
It might be a good idea to mention that dependency in readme.
Thanks!
