### ISSUE TITLE
display of albums and pictures is off

### ISSUE THREAD

**Issue by tessus** [tkuther/piwigo-bootstrap-darkroom#21]
I'm not sure, if this is an issue with the theme or not, so please bear with me.

If there are albums and pictures on a page, the albums are shown first and then the pictures. This is fine, but the problem is as follows:

Depending on the width of the browser window the pictures start to vanish. Also the pictures are only shown in the columns where there's no album.

Here's an [example](https://gallery.evermeet.cx/index/category/47).

As you can see the last picture is not in the beginning of the second row. If you make the width of the browser smaller, you'll see that the pictures start to vanish and only the albums remain.

If this is not a theme issue, please let me know and I file a bug with the piwigo.

**Comment by tkuther** [comment]
Hi @tessus,

this is a known issue with the GThumb+ plugin, see #14. Unfortunately the only workaround is to use gdThumb instead or not use "super albums" (those containing both pictures and sub albums) at all.

I'll close this as a duplicate.
