### ISSUE TITLE
Empty toggle second menu

### ISSUE THREAD

**Issue by titounet** [tkuther/piwigo-bootstrap-darkroom#210]
Hello,
On screen < 1000 px large, the second menu in the second bar appear when there's no function / item (example : about page, notification page, add pages made with additionnal page plugin, etc.)

Best regards,

Pierre
![scm](https://user-images.githubusercontent.com/567711/58975247-ce89fc00-87c4-11e9-888f-bcaceb96d067.PNG)

**Comment by tkuther** [comment]
That's to be expected, and I wouldn't call it a bug
