### ISSUE TITLE
disable right click won't work under slide mode

### ISSUE THREAD

**Issue by wuye55** [tkuther/piwigo-bootstrap-darkroom#211]
Hi,

I have an issue, in slide play, I can't disable right mouse click 'save image as', i.e. anyone can download image. It only occurred in PhotoSwipe mode and if I used Piwigo default, that works fine. I really like PhotoSwipe mode and please help if anyone has a good idea to fix it. Thanks a lot!

Wuye

**Comment by tkuther** [comment]
You need to configure the rightClick plugin. Your browser's Dev tools are your friend.
This is what I have:
```
$conf['rightClick_selectors'] = array(
  '.placeholder img',
  '.leaflet-popup-content img',
  '.videocontent',
  '#wrapper',
  );
```

**Comment by wuye55** [comment]
Hi Thomas,

thanks for our suggestions, but I am just a beginner. 'Right click plugin'
not allow user to config . Could you give  me a step by step instruction
how to configure right click using Chrome Dev tools?. Thanks for your time!

Best,
Gong

**Comment by wuye55** [comment]
Hi, I tried add your code into 'main.inc.php' under right click plugin, but it didn't work. I know I did something wrong. Please advise. Thanks!

**Comment by tkuther** [comment]
Use LocalFiles Editor plugin.

**Comment by wuye55** [comment]
Hi I tried using LocalFiles Editor plugin, either add your code in 'bootstrap_darkroom-rules.css' or in 'config.inc.php', but problem still same. Any idea? Thanks!

**Comment by wuye55** [comment]
Hi, if you get chance, please let me why is not working with my configure. thanks!

**Comment by tkuther** [comment]
Do you have the edited version above with `.pswp`?

**Comment by wuye55** [comment]
thanks for reply! I am not quite sure what it is and seems I don't have.
That somehow edit tool, what is full name? I probably can get one if need.

**Comment by tkuther** [comment]
I mean the edited comment above. Use github in browser..
