### ISSUE TITLE
Nothing shows on Category List page

### ISSUE THREAD

**Issue by srtoys** [tkuther/piwigo-bootstrap-darkroom#212]
I created a Category list page per the documentation on wiki using the Additional Page plugin.
The new page shows up but it does not show the categories or the images.
I manually ran the api calls and it returns the correct data.
I attached a screenshot of the result and the source.

Any ideas?

![category-list](https://user-images.githubusercontent.com/42153265/59382378-9423e000-8d2b-11e9-8cce-e3e801267dd9.jpg)
![category-list-source](https://user-images.githubusercontent.com/42153265/59382381-9423e000-8d2b-11e9-97cf-72d4bcc32eed.jpg)

**Comment by tkuther** [comment]
Check your browser's dev tools console for errors. This is advanced stuff..
