### ISSUE TITLE
Question regarding Photoswipe an Ajax

### ISSUE THREAD

**Issue by Schmidtze2** [tkuther/piwigo-bootstrap-darkroom#215]
Hi,

I'm a bit confused: This picture page has a transfer size of about 1 MB: 

[https://friedemanns.photos/picture.php?/35419/category/870&key=505c419d976211e9b07fac1f6b7a83ea](https://friedemanns.photos/picture.php?/35419/category/870&key=505c419d976211e9b07fac1f6b7a83ea)

But at home, on my local XAMPP, it has about 9 MB. As I first noticed the 9 MB and I saw that the photoswipe data for all images in this album (nearly 10.000 images) will be downloaded at once, I began to change it to load the photoswipe data after pressing the slideshow button by using an Ajax request. A first version works already, it's now about 800 KB for this page on my local server. Now I noticed that it is already nearly the same on the server.

My question: Does it use Ajax already to load the phptoswipe data for all images in the same album? Do you have an idea why it works on the server, but not a t home on my local server?

In picture.tpl there is this:

```
{if !$derivative->is_cached()}
  {combine_script id='jquery.ajaxmanager' path='themes/default/js/plugins/jquery.ajaxmanager.js' load='footer'}
  {combine_script id='thumbnails.loader' path='themes/default/js/thumbnails.loader.js' require='jquery.ajaxmanager' load='footer'}
{/if}

```
Is this the reason for loading only 1 MB from the server first? And why doesn't it work at home on the local server? Do you have an idea?

Best regards
Schmidtze

**Comment by tkuther** [comment]
It could be missing gzip compression. With 10k+ photos, the DOM might get huuuuuge.

**Comment by Schmidtze2** [comment]
You are absolutely right, the gzip compression was not enabled. Honestly I didn't know that this exists and that it can be enabled/disabled. It#s new for me, that a compressin can be done already on the server...

Thank you so much
Friedemann

**Comment by tkuther** [comment]
The difference is huge, indeed.

Loading everything via AJAX on demand has been on my list ever since, but the Piwigo API doesn't expose everything needed, yet. So we fire one insanely costy MySQL query on page load, and use smarty to push everything into DOM (which in the end is plain text, so gzip compression works OK here)

It's a costy theme, requires well configured database and webservers, especially for large galleries. That's the price.
