### ISSUE TITLE
Fixed image ID on a selectable photo corner

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#218]
I would like to add this suggestion, many times when speaking over the phone about a photo its not easy to comunicate the exact one to chat about it.
Given that every photo has a photo ID, it would be great if an always visible overlay in a small corner of each expanded photo is shown, here is a mockup I made.
I made it red, but matching the theme colors would be better of course.
![image](https://user-images.githubusercontent.com/25783916/60757303-2e034380-9fdf-11e9-99db-92884c1ad2bc.png)

thanks!

**Comment by tkuther** [comment]
Should be possible with a custom plugin.

**Comment by pablopeu** [comment]
Sadly don't know how to code it. Thanks Thomas.
