### ISSUE TITLE
Login and password entry form does not open, menu navigation does not work

### ISSUE THREAD

**Issue by Pitstopper** [tkuther/piwigo-bootstrap-darkroom#219]
Hey. I switched to Piwigo from Flickr with their 1000 photo limit. Setting up a Piwigo for myself, I set your theme as default, but I ran into one unpleasant bug (?). After one of the template updates, the login and password entry form does not appear in the menu, navigation through the remaining menu items also does not work.

Piwigo version - 2.9.5
Bootstrap Darkroom - 2.4.1

**Comment by tkuther** [comment]
Please clear your compiled templates cache after updates.
