### ISSUE TITLE
Updates to default - 1.0.5

### ISSUE THREAD

**Issue by Philio** [tkuther/piwigo-bootstrap-darkroom#22]
I released a few updates today, might be some duplicate code you can remove (saw a reference in one of the PRs):

https://github.com/Philio/bootstrapdefault/compare/release/1.0.4...release/1.0.5

**Comment by tkuther** [comment]
Thanks, Phil! Will see what can be cleaned up in darkroom then.

**Comment by tkuther** [comment]
Cleanups done in 1.5.1
