### ISSUE TITLE
Too many buttons for REAL fullscreen (Suggestion)

### ISSUE THREAD

**Issue by danilort** [tkuther/piwigo-bootstrap-darkroom#220]
To activate the real fullscreen mode, I have to press too many buttons.

Current behavior:
	• from the photo page, press the button"Fullscreen"
	• press the button "Toggle fullscreen" (show the photo with black margins)
	• press the button "Zoom in/out" (OK, it's in real fullscreen)
	• press the button "Next"  (show the photo with black margins)
	• press the button "Zoom in/out" (OK, it's in real fullscreen)
	• Next
	• Zoom in/out
	• ...

My suggestion:
	• from the photo page, press the button"Fullscreen"  (OK, it's in real fullscreen)
	• press the button "Next" (OK, it's in real fullscreen)
	• press the button "Next" (OK, it's in real fullscreen)
	• ...

My configuration:
	Bootstrap Darkroom 2.4.1
	Piwigo 2.9.5
	Windows 10
	Firefox 68

**Comment by tkuther** [comment]
zoom != real fullscreen

You are in fullscreen after 2nd click.
