### ISSUE TITLE
2.10.0RC1: Error when opening Comments using Bootstrap Darkroom theme

### ISSUE THREAD

**Issue by jheinitz** [tkuther/piwigo-bootstrap-darkroom#221]
Hello!

I have an issue with this theme and with the latest Piwigo version 2.10.0RC1. I already created an issue in the Piwigo repository, but maybe it is helpful to have the issue here as well. This is the link to the Piwigo issue: https://github.com/Piwigo/Piwigo/issues/1067

Kind regards

Jens

**Comment by plegall** [comment]
Isn't it related to https://piwigo.org/doc/doku.php?id=dev:changes_in_2.10#no_more_include_for_comment_listtpl ?

**Comment by tkuther** [comment]
@plegall thanks for that link. So, there will be a new release tagged compatible with 2.10 only

**Comment by plegall** [comment]
Actually you can do:

```
{if isset($COMMENT_LIST)}
  {$COMMENT_LIST}
{else}
  {include file='comment_list.tpl'}
{/if}
```

To be compatible with both Piwigo 2.9 and 2.10 :-)
