### ISSUE TITLE
[User Collections] create collection input is broken

### ISSUE THREAD

**Issue by plegall** [tkuther/piwigo-bootstrap-darkroom#226]
Hi @tkuther 

As opposed to what's written in #76 the support for User Collections is nearly full with Bootstrap Darkroom, which is a really good thing :-) Here is a little something that's still buggy.

When trying to create a new collection from a thumbnail, the input field does not appear.

![20190905-bootstrap_darkroom-user_collection-bug-new-collection](https://user-images.githubusercontent.com/9326959/64332029-23136200-cfd4-11e9-8930-6498ff0d0240.gif)

I know it can be fixed, and this is what has been done a this modified Bootstrap Darkroom theme:

![20190905-bootstrap_darkroom-user_collection-bug-new-collection-fixed](https://user-images.githubusercontent.com/9326959/64332100-3d4d4000-cfd4-11e9-8767-c9220c13ad6e.gif)

I've studied the difference in code for more than one hour now and I don't understand what changed need to be applied.

I'm notifying the author of the modified theme, hoping he can explain and how it can be fixed for everybody :-)

**Comment by tkuther** [comment]
Hi @plegall 

Looks like I killed an event toggle for
```
#collectionsDropdown .remove, #collectionsDropdown input.new {
    display: none
}
```
(https://github.com/mistic100/Piwigo-User-Collections/blob/95ecf20f050b93b8db7c6400df6b5ee867aa02d2/template/style_thumbnails.css#L46)

There is an o'clock here: https://github.com/mistic100/Piwigo-User-Collections/blob/95ecf20f050b93b8db7c6400df6b5ee867aa02d2/template/thumbnails_css_js.tpl#L12

Maybe got lost somehwere

**Comment by tkuther** [comment]
Fixed in master
