### ISSUE TITLE
Theme doesn't work with photo sphere plugin

### ISSUE THREAD

**Issue by diba78** [tkuther/piwigo-bootstrap-darkroom#227]
Hi all together,

i tried tu use the photo sphere plugin to view my insta360 photos with the Bootstrap Dark Theme.

The photo is tagged with the photo sphere tag

But it doesn't work when i try to open the photo (see picture).

With other themes like elegant or Bootstrap default the photo sphere plugin works fine.

Can anybody help me. Have i configure something wrong ?

Best regards

Dirk
![Bootstrap_dark_with_photosphere](https://user-images.githubusercontent.com/44620652/64449002-42e37c80-d0df-11e9-8de1-f8e89fd8ff36.JPG)

**Comment by djgreg13** [comment]
On my side i removed two block
`{if $theme_config->social_pinterest}
        <a href="https://www.pinterest.com/pin/create/button/?url={$http_scheme}://{$smarty.server.HTTP_HOST}{$smarty.server.REQUEST_URI}&media={$http_scheme}://{$smarty.server.HTTP_HOST}{$smarty.server.REQUEST_URI}/../{$current.selected_derivative->get_url()}"
           onclick="window.open(this.href, 'pinterest-share', 'width=490,height=530');return false;" title="Pin on Pinterest"{if $theme_config->social_buttons} class="btn btn-sm btn-social btn-raised btn-pinterest"{/if}>
            <i class="fab fa-pinterest"></i>{if $theme_config->social_buttons} Pinterest{/if}
        </a>
{/if}
{if $theme_config->social_vk}
        <a href="https://vkontakte.ru/share.php?url={$http_scheme}://{$smarty.server.HTTP_HOST}{$smarty.server.REQUEST_URI}&image={$http_scheme}://{$smarty.server.HTTP_HOST}{$smarty.server.REQUEST_URI}/../{$current.selected_derivative->get_url()}"
           onclick="window.open(this.href, 'vk-share', 'width=490,height=530');return false;" title="Share on VK"{if $theme_config->social_buttons} class="btn btn-sm btn-social btn-raised btn-vk"{/if}>
            <i class="fab fa-vk"></i>{if $theme_config->social_buttons} VK{/if}
        </a>
{/if}`

the selected_derivative not exists with plugins which modifie the picture renderer

**Comment by tkuther** [comment]
@djgreg13 good finding! Disabling social integration in theme config should remove that block
