### ISSUE TITLE
Cyrillic encoding

### ISSUE THREAD

**Issue by konservat0r** [tkuther/piwigo-bootstrap-darkroom#23]
Hello!

breadcrumbs do not show correct words where the сyrillic encoding? =(

![12865164](https://cloud.githubusercontent.com/assets/25728333/22865754/7c0a90f2-f17b-11e6-9fc9-89e0ccc33358.jpg)

**Comment by tkuther** [comment]
Please test and reopen if this does not fix it. Thanks!

**Comment by konservat0r** [comment]
thank you very much, fix it =)
