### ISSUE TITLE
Tags with : as well as . not displaying properly

### ISSUE THREAD

**Issue by sridharb1** [tkuther/piwigo-bootstrap-darkroom#232]
Problem 1: I have a tag like "Lens: Canon EF 24-70 f2.8L II USM". This is split into two tags in the database: Lens: Canon EF 24-70 f2 and 8L II USM.

Problem 2: I have tags like "Aperture: Low". This only displays "Low" in the photo page. Whereas the database contains "Aperture: Low".

I suspect that Problem 2 is the Theme and Problem 1 is a more deep-rooted issue (which I can avoid by not using .).

Could you guide me on how Problem 2 can be fixed?

I am using the latest version of the theme.

**Comment by tkuther** [comment]
Can you test this with a different theme?

**Comment by sridharb1** [comment]
Thanks, I did now and see that the same behavior is across different themes.
Could you please point me to where the tags variable that you use is being populated? Maybe I can glean where the code is stripping off the text before :.
Thanks,Sridhar

    On Friday, 11 October, 2019, 1:25:23 pm IST, Thomas Kuther <notifications@github.com> wrote:  
 
 
Can you test this with a different theme?

**Comment by sridharb1** [comment]
Please close this as this is not a specific issue with this theme. I would still appreciate your insight as to where this problem originates from.
