### ISSUE TITLE
empty space 

### ISSUE THREAD

**Issue by konservat0r** [tkuther/piwigo-bootstrap-darkroom#24]
Hello, tkuther

there was a problem with empty space on some pages
![screenshot 2017-02-13 002](https://cloud.githubusercontent.com/assets/25728333/22874331/7b6db5c4-f1d6-11e6-869f-aba1fc634cff.png)
![screenshot 2017-02-13 003](https://cloud.githubusercontent.com/assets/25728333/22874368/ad61359c-f1d6-11e6-890f-9a4772a73eff.png)

![screenshot 2017-02-13 001](https://cloud.githubusercontent.com/assets/25728333/22874228/fabdc54a-f1d5-11e6-8960-b5d894f0a8e7.png)

strange that it occurs not on all pages

http://www.photo.yurevets37.ru/picture.php?/1962/category/41
http://www.photo.yurevets37.ru/picture.php?/1845/category/41
http://www.photo.yurevets37.ru/index.php?/category/31

**Comment by tkuther** [comment]
This happens if there is a warning shown on the page, but hidden by the sticky-top navbar.

In the html source for the first link I can see a warning related to #25.

**Comment by tkuther** [comment]
PS: as a quick workaround, set ```display_errors = Off``` in php.ini

**Comment by konservat0r** [comment]
Created in php.ini subdomain root has written your code, but errors remained =(

**Comment by tkuther** [comment]
Then maybe try setting ```$conf['show_php_errors'] = ''``` in Piwigo's local/config/config.inc.php

In any case, the real error that causes the PHP error notice should be fixed in Piwigo core, as mentioned in #25

**Comment by konservat0r** [comment]
Its work! error disappeared. it remains to find who creates it
