### ISSUE TITLE
strip_tags() expects parameter 1 to be string

### ISSUE THREAD

**Issue by konservat0r** [tkuther/piwigo-bootstrap-darkroom#25]
bug found only in the album "Коллективные фотографии"

http://www.photo.yurevets37.ru/index.php?/category/33

![screenshot 2017-02-13 004](https://cloud.githubusercontent.com/assets/25728333/22874795/2ef60c48-f1d9-11e6-86e7-66bf5a225fd3.png)

`Warning: strip_tags() expects parameter 1 to be string, array given in /home/konse863/domains/yurevets37.ru/public_html/photo/include/functions_metadata.inc.php on line 205`

**Comment by tkuther** [comment]
This seems to be a Piwigo core issue.

The relevant code block from include/functions_metadata.inc.php:
```
  if (!$conf['allow_html_in_metadata'])
  {
    foreach ($result as $key => $value)
    {
      // in case the origin of the photo is unsecure (user upload), we remove
      // HTML tags to avoid XSS (malicious execution of javascript)
      $result[$key] = strip_tags($value);
    }
  }
```

As a quick workaround, try setting ```$conf['allow_html_in_metadata'] = true``` in local/config/config.inc.php

Please open a ticket in core https://github.com/Piwigo/Piwigo for this one. I think it's an issue with the metadata format in of your pictures. If you can find it, that will be helpful.
