### ISSUE TITLE
<h1>Header</h1>

### ISSUE THREAD

**Issue by konservat0r** [tkuther/piwigo-bootstrap-darkroom#26]
Dear tkuther, is it possible to to make a header image, album, category` <h1>Header</h1>` or do not need? =)

![screenshot 2017-02-13 001](https://cloud.githubusercontent.com/assets/25728333/22893118/e6770042-f225-11e6-97cc-5e814ffbc40d.png)

**Comment by tkuther** [comment]
Actually, the breadcrumbs serve as the page title. Though, thats not the SEO-friendliest way.

Where would you expect that header to be? Between the image an the navigation buttons?
If so, you could
1.) create folder _template-extensions/bootstrap_darkroom_
2.) copy _themes/bootstrap_darkroom/template/picture_nav_buttons.tpl_ to _template-extensions/bootstrap_darkroom/_
3.) edit it, e.g. add ```<h1>{$SECTION_TITLE}${LEVEL_SEPARATOR}{$current.TITLE}</h1>``` at the top
4.) in Administration -> Configuration -> Templates, choose the customized template, original template is picture_nav_buttons.tpl again, and assign it to bootstrap_darkroom theme

**Comment by konservat0r** [comment]
Yes, can the image title be duplicated after the image? It would be convenient for visitors and for SEO. 

I used your method, so/Auto/Porsche :) I don't know how the headline will look like Google. =)
![screenshot-13feb2017-23 59 39](https://cloud.githubusercontent.com/assets/25728333/22903112/954547d8-f248-11e6-9aa0-c6551b4f3f79.png)

```
<h1><a href="/" title="Начало"><i class="fa fa-home" aria-hidden="true"></i></a ><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body> / <a href="index.php?/category/155">Auto</a></body></html>
 / Porsche</h1>
```

I am too embarrassed to ask, probably am going to be bothersome, but how can I insert a Russian social network for sharing ratio (instead of or next to Google, facebook). Perhaps there is a way to paste the code in the template?

```
<script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
<script src="//yastatic.net/share2/share.js"></script>
<div class="ya-share2" data-services="collections,vkontakte,facebook,odnoklassniki,moimir" data-counter=""></div> 
```https://tech.yandex.ru/share/

Thank you for your help and quick response!

**Comment by tkuther** [comment]
Below the image there is the Image description if available (from metadata). 

The Share Buttons come from the parent theme and are quite hardcoded. You could use custom javascript/jquery to insert it there. Check the wiki here.
