### ISSUE TITLE
add a sitewide footer

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#27]
Is it possible to add this kind of footer so its visible across the site?

http://tutorialzine.com/2015/01/freebie-5-responsive-footer-templates/

Thanks!

**Comment by tkuther** [comment]
You can use the plugin perso footer from http://piwigo.org/ext/extension_view.php?eid=554

**Comment by pablopeu** [comment]
But perso pluging allows to add more than just a line? I want to add an
HTML5 footer with contact info and more. Thanks

**Comment by tkuther** [comment]
Yes, any HTML code.

Quoting my reply mail on the mail you sent me:

> 1) Download the freebee footer stuff you posted
> 2) choose for example the 
> footer-distributed-with-address-and-phones.html and open it in an editor
> 3) copy anything from <footer ... </footer> into PersoFooter text box
> 4) open the CSS file css/footer-distributed-with-address-and-phones.css 
> and copy all
> 5) in PersoFooter add inline style, so things loo like:
> 
> ```
> 
> <footer class="footer-distributed">
> blabla
> </footer>
> 
> <style type="text/css>
> 
> .copyright {
>     padding: 0;
>     width: 100%;
> }
> 
> 
> /* paste right here */
> 
> 
> </style>
> ```

**Comment by pablopeu** [comment]
You would be proud of me!!! made it work: www.peu.net Thanks!!!

Tried to combine into it the advanced description codes for multiple
languages but the moment I use them the whole html dissapears. Besides this
it works!!!

I owe you a beer or two!! do you have a paypal.me address?

Cheers!

**Comment by tkuther** [comment]
You're welcome. No need for beer donations, I live in Bavaria :) Just donate to Piwigo if you like to.
To make the footer full with and stick to bottom, add this inside the style tags:
```
.copyright {
    padding: 0;
    width: 100%;
}
```

**Comment by pablopeu** [comment]
Thanks Thomas.

Added the suggested CSS but nothing changes, its something elsewhere,
because if you load the same code as a standalone page its full width:

http://peu.net/cuchillos/themes/footerpeu/footer.html

What I did is replace perso footer (kept it just for a single line
copyright notice) with PWG stuffs plugin, solved the minor quirks and works
the same.

Cheers

**Comment by pablopeu** [comment]
Thomas, after looking and looking I found that the page title is a read and
asigned in the header.tpl file of the theme, but found no way (lack of
coding skills) to put a proper title there, can you consider the posibility
of adding the option of having a page title in text mode and a page
logotype as I have now?

Thanks!!

**Comment by tkuther** [comment]
An option for using a logo image instead of text-only is on the TODO list.

**Comment by pablopeu** [comment]
excelent news. now I wait.. THanks!!!

**Comment by tkuther** [comment]
Tracked in #36

**Comment by pablopeu** [comment]
Hi Thomas, sorry for bother you about this, if you can help it will be
appreciated, I used the freebie footer, but no matter what I try its
missaligned, and on categories it covers the last pictures. Do you think
its the HTML, the CSS or something else?

Thanks!!
