### ISSUE TITLE
Compatibility with Piwigo 11

### ISSUE THREAD

**Issue by TmCrafz** [tkuther/piwigo-bootstrap-darkroom#270]
Hello together,
is the theme compatible with the new Piwigo 11 Version?
The backend is telling me before updating that the actual installed Version is not compatible.

**Comment by jangrewe** [comment]
I took the leap and upgraded, seems to work fine - at least i haven't noticed any problems yet.

**Comment by jheinitz** [comment]
Moin!

Basically it works with Piwigo 11, but I'm struggling with the display of
the related albums. These are completely expanded and make it unreadable.
But I did not spent too much time on it yet.

Best regards

Jens

Am Fr., 22. Jan. 2021 um 20:45 Uhr schrieb Jan Grewe <
notifications@github.com>:

**Comment by readonly24** [comment]
I'm waiting to update Piwigo until my favourite theme is compatible.

**Comment by jheinitz** [comment]
Same with me. I have a "sandbox" installation where I test before upgrading
my "real" installation.



Am Sa., 23. Jan. 2021 um 18:26 Uhr schrieb readonly24 <
notifications@github.com>:

**Comment by TmCrafz** [comment]
Thanks to you all for testing it. I just updated my productive piwigo installation too and everything works so far

**Comment by prolibre** [comment]
Hello,
For me the theme works except for the ""Related Albums"" menu which does not work on pages where there are photos and albums.
You can fix this problem by disabling this menu in the administration (Configuration / Menu).

I love this theme and by the way I thank its author.
