### ISSUE TITLE
ask/comment about a photo via email?

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#29]
Now that I'm starting to use the piwigo as my main gallery with the darkroom theme I find the social buttons a great option, since its already being used by customers to ask about a certain photo. 
What would be great is to be able to do the same via email, say for example, if you press the email button an email (mailto:) would be composed with a link to the photo.

www.peu.net

btw, just updated to your latest release, thanks for keeping it active!!!

**Comment by tkuther** [comment]
You can add custom share buttons quite easily without modifying any template files.
See https://github.com/tkuther/piwigo-bootstrap-darkroom/wiki/Add-custom-share-buttons for an example.

It could cause a short moment of "mhm, what??", but if that's the case I can try to explain it a bit better :-)

**Comment by pablopeu** [comment]
I managed to add the plugin, the mailto and a subject, but what its missing
is the link to the image from where the mailto was triggered, like what
happens when you press the big 3 ones, thats the beauty of the other 3
icons, a FB user clicks and s/he can send me the link to the photo.

Regarding the search box, I see that you commited a change, will check how
it works on the next update, thanks. in the meantime I hacked my solution,
like using a cleaver to modify the code, but in the end it worked, edited
search.tpl so the only search box are tags LOL, not the best but in the
meantime should make things easier to users LOL

www.peu.net

Cheers!!

**Comment by tkuther** [comment]
The link to the image can be inserted using javascript window.location, like

`.apped('<a href="mailto:me@xy.com?subj=Your%20Photo%20at%20 ' + window.location" title=... ...');`
