### ISSUE TITLE
Slideshow\Expand on IE11 \ Win 10

### ISSUE THREAD

**Issue by ShazBux** [tkuther/piwigo-bootstrap-darkroom#3]
Hi, some issues i have seen when using IE11:

When clicking the slideshow button from the album page i get the following error: "picture identifier is missing", redirected to home page after a few seconds.
When on a picture page nothing happens when clicking the slideshow or expand buttons

Tested on the latest revision - 1.2.1

Flawless on Chrome - great work!

Let me know if you need any more info.

Thanks
Shaz

**Comment by tkuther** [comment]
Thanks for the report, Shaz.

I was able to reproduce it in a Windows 10 VM with IE11, but I must admit that, even after going through the page with F12 dev tools mode, I have absolutely no idea what's going wrong with IE11 here. The page is actually totally broken with it. Even IE 11 Mobile on Windows Phone 8.1 works better.
Edge works just fine. I guess there was a reason to bury IE.

Pull requests welcome, but I can't/won't spent time operating a dead horse.

I'll leave the issue open, though.

**Comment by tkuther** [comment]
Nevermind, I found the issue. A fix will be in the next version.
