### ISSUE TITLE
No quick search on mobile (IOS)

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#30]
for an user who uses the site on the desktop and mobile it can be confusing. For example, if you are used to search by tag, if on IOS you open menu>search the first field the tag search is disabled, I guess because below it is the sag search.
On the desktop the user would have no need to go to the search menu because quick search finds everything, tags included.

Cheers.

**Comment by tkuther** [comment]
You do have a point here.
