### ISSUE TITLE
Google adsense

### ISSUE THREAD

**Issue by zorodimanche** [tkuther/piwigo-bootstrap-darkroom#31]
I have a PIWIGO gallery and I want to monetize my site to pay the fees (domane name, hosting, maintenance ...) but when I searched on piwigo.com there is no plugin to insert Ad site for google adsense. Can you integrate it into the development please to make my site live. Thank you

**Comment by tkuther** [comment]
Please use Plugin PWGStuffs, PersoFooter, or simply use the Jumbotron banner feature which is available in theme settings.
