### ISSUE TITLE
Meta description

### ISSUE THREAD

**Issue by zorodimanche** [tkuther/piwigo-bootstrap-darkroom#34]
Integrate into the theme the possibility of integrating a meta description

**Comment by tkuther** [comment]
Meta description is supported, but the logic behind it is totaly bonkers upstream in Piwigo core.

**Comment by pablopeu** [comment]
If you want to add <meta> such as the open graph ones you can use the add to head plugin:
http://piwigo.org/ext/extension_view.php?eid=582

**Comment by konservat0r** [comment]
@pablopeu Help what to put in the Open Graph to the picture and description are displayed correctly :)

```
<meta property="og:type" content="website">
<meta property="og:site_name" content="Site_name">
<meta property="og:title" content="Title">
<meta property="og:description" content="Description.">
<meta property="og:url" content="http://example.com/page.html">
<meta property="og:locale" content="ru_RU">
<meta property="og:image" content="http://example.com/img.jpg">
<meta property="og:image:width" content="968">
<meta property="og:image:height" content="504">
```

**Comment by pablopeu** [comment]
OG Meta does not help, they are all there, open www.peu.net and check page
source :)

**Comment by konservat0r** [comment]
@pablopeu Dear friend, you have the same descriptions, images, headers on all pages :( And how to make so that they were taken to a page?

**Comment by pablopeu** [comment]
Sergey, there is a plugin where you can add elements to the <head> its
called "Add < head > element"

**Comment by konservat0r** [comment]
I know about the plugin, I need been to a different image and description for each page. You did not understand me :(

**Comment by tkuther** [comment]
OK. I added a workaround that bypasses the broken $meta_ref handling in core and the heck just sets author and description if available.

If you really want Open Graph data, create a local_head.tpl in themes/bootstrap_darkroom/ and add stuff there. For individual image, see meta stuff example in header.tpl ($COMMENT_IMG, $INFO_AUTHOR variables can be re-used here)

**Comment by konservat0r** [comment]
@tkuther did not find of the variable image, it is difficult to understand without programming skills :(

`<meta property="og:type" content="website">
<meta property="og:site_name" content="$TITLE">
<meta property="og:title" content="$PAGE_TITLE">
<meta property="og:description" content="$CONTENT_DESCRIPTION">
<meta property="og:url" content="$current.path">
<meta property="og:locale" content="ru_RU">
<meta property="og:image" content="?">
<meta property="og:image:width" content="968">
<meta property="og:image:height" content="504">`
