### ISSUE TITLE
Quick search on narrow screens

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#38]
Thanks for the update!
On narrow screens, such as mobile, the quicksearch box does not take into consideration the height of the page logo defined in darkroom and overwrites anything thats taller than the menu.

A solution could be the one used by header manager plugin which defines the size before the upload.
(I know, another solution would be making a page logo not taller than the menu, but logo would be rather tiny...)

**Comment by tkuther** [comment]
That hasn't anything to do with the quicksearch. If you disable it, then that vertical divider will overlay the image. In Bootstrap, the navbar has a fixed height, and the collapsed menu on mobile is faded in at a certain position.

If you want it to be taller, use custom CSS like
```
.navbar-main {
  min-height: 80px;
}
.navbar-main .navbar-collapse {
  margin-top: 50px;
}
```
(adjust values to the height of you image, above values seem to work in your case)

**Comment by pablopeu** [comment]
Thanks Thomas!! it works nicely on mobile, but on desktop it creates an
innecesary empty space, if its the solution will have to live with it ☺

**Comment by tkuther** [comment]
You can use a media query to affect only mobile devices, like so:
```
@media (max-width: 767px) {
  .navbar-main {
    min-height: 80px;
  }
  .navbar-main .navbar-collapse {
    margin-top: 50px;
  }
}
```

**Comment by pablopeu** [comment]
Thank you, thank you, thank you, are you sure about the beer thing?
Cheers!!!
