### ISSUE TITLE
[feature request] setting destination for logo image click

### ISSUE THREAD

**Issue by arigit** [tkuther/piwigo-bootstrap-darkroom#39]
Currently Bootstrap Darkroom allows configuration of the logo image, and it can be manipulated via CSS in "bootstrap default".
The logo image is automatically made a clickable link - the href destination though is hardcoded to piwigo's landing page (same destination as the Home icon that Bootstrap Darkroom displays so kind of redundant).
In my use case, Piwigo is a sub-site of my blog, and I need to customize the logo link to have it point to the landing page of the blog (which is wordpress in my case).
Is it possible to add a configuration entry to (optionally) set the destination URL of the logo image link?

**Comment by tkuther** [comment]
As this is a very specific use case, I think it's overkill to make this configurable.

You can use a very simple custom javascript as explained here: https://github.com/tkuther/piwigo-bootstrap-darkroom/wiki/Add-custom-CSS-and-Javascript#javascript
The jQuery code:
```
$('a.navbar-brand').attr('href', 'http://yoursite.com');
```

**Comment by arigit** [comment]
Thank you for this, it worked. 
Fully agreed most ppl won't need this, and the workaround fits the bill perfectly, without having to tweak the theme itself.
Closing :)

**Comment by arigit** [comment]
p.s. suggest adding this to the wiki, I tried but couldn't edit it.
