### ISSUE TITLE
Plugin "Batch Downloader" not working with Bootstrap Darkroom theme

### ISSUE THREAD

**Issue by thuner-li** [tkuther/piwigo-bootstrap-darkroom#4]
Plugin Batch Downloader (Version 2.2.2) not working with Bootstrap Darkroom theme (no action on icon).

Link to Plugin: http://piwigo.org/ext/extension_view.php?eid=616

Piwigo: 2.8.1
PHP: 5.5.19 (Info anzeigen) [2016-06-05 14:22:20]
MySQL: 5.5.40 [2016-06-05 14:22:20]
Grafikbibliothek: External ImageMagick 6.3.5

Tested Browser: 
- Chrome 50.0.2661.102 m 
- Firefox 46.0.1

**Comment by tkuther** [comment]
This plugin is supported and should work. It does here in all tested browsers.

But it does require a lot of jQuery voodoo, and maybe you are seeing an error I don't. Could you please ckeck your site with chrome dev tools (shift+ctrl+i) and see if there are any javascript errors?

**Comment by thuner-li** [comment]
Hi,
as I can see, is there no error. I don't have a menu like you:

![batch_downloader](https://cloud.githubusercontent.com/assets/19760474/15807123/4002844e-2b55-11e6-8169-5caf0a2ea8db.PNG)

Here is the section:

`
<li class="dropdown open"><a href="#" id="batchDownloadLink" title="Alle Bilder dieser Auswahl herunterladen" class="dropdown-toggle" rel="nofollow" data-toggle="dropdown" aria-expanded="true">
  <span class="pwg-icon batch-downloader-icon" style="background:url('./plugins/BatchDownloader/template/images/zip.png') center center no-repeat;">&nbsp;</span><span class="pwg-button-text">Herunterladen</span><span class="caret"></span>
</a>
</li>
 `

With Bootstrap Default I get a message (even there I do not have menue as you mentioned): 

![batch_downloader_default](https://cloud.githubusercontent.com/assets/19760474/15807153/23df864e-2b56-11e6-8a11-c84dd917f5c2.PNG)

In case of Bootstrap Default I can see the following on the console:

`
VM7448:1 Resource interpreted as Document but transferred with MIME type application/force-download: "https://wimpelfisch.ch/plugins/BatchDownloader/download.php?set_id=26&zip=1".
`

**Comment by tkuther** [comment]
So, with Bootstrap Default, clicking on the icon will directly start the download? 

What does your configuration look like in Batch Downloader settings -> Download permissions -> Auswahl Bildgröße? Jede Größe, oder Einheitsgröße? (..das jetzt weiter vom Deutschen zurück ins Englische zu übersetzen ist wohl unnötig :-))

**Comment by tkuther** [comment]
Ich konnte es reproduzieren. Es lag tatsächlich an der Berechtigung ob jede größe, oder nur eine voreingestellte.

Als Schnell-Fix bitte die plugin_fixes.js von https://raw.githubusercontent.com/tkuther/piwigo-bootstrap-darkroom/b9dfb2aa84975955955d6c686fdfbfbc6ccb84fc/js/plugin_fixes.js kopieren nach themes/bootstrap_darkroom/js/

**Comment by thuner-li** [comment]
Besten Dank für den schnellen Fix, funktioniert wunderbar!

**Comment by CRi83** [comment]
It looks like batch downloader is partially broken since update 2.0.7 of bootstrap-darkroom.
It works when you download a single picture, but at the gallery level, the download buttons is missing.

Picture level:
![image](https://user-images.githubusercontent.com/11972271/31855288-885e9d06-b6a8-11e7-9b9a-68f6b045b923.png)

Gallery level:
![image](https://user-images.githubusercontent.com/11972271/31855300-b7e875ce-b6a8-11e7-814d-8f971845346f.png)

**Comment by tkuther** [comment]
That's the batch downloader icon:
![bildschirmfoto 2017-10-21 um 22 07 09](https://user-images.githubusercontent.com/63717/31855474-34c39d46-b6ac-11e7-843f-c5ccb732357c.png)

**Comment by CRi83** [comment]
Hi tkuther,

Ok so it's not appearing at all then.
Is this a known issue?

**Comment by tkuther** [comment]
No, it works fine here.

**Comment by CRi83** [comment]
It looks like the button is actually there, but not rendered properly.
![image](https://user-images.githubusercontent.com/11972271/31888504-9eab776e-b7fc-11e7-878d-bdd5e9fa1c94.png)

**Comment by tkuther** [comment]
Do you get any javascript errors in the console in developer tools?

**Comment by tkuther** [comment]
Nevermind. I found the issue. Fixed in next version

**Comment by CRi83** [comment]
Great, thanks very much !

**Comment by microcryon** [comment]
> The problem only appears when batch-downloader is setup to allow only one size of photo: ![image](https://user-images.githubusercontent.com/11972271/31888871-fc0de8aa-b7fd-11e7-941e-3e8f3e2b125c.png)
> 
> In that case, the button is actually there, but not rendered properly: ![image](https://user-images.githubusercontent.com/11972271/31888504-9eab776e-b7fc-11e7-878d-bdd5e9fa1c94.png)

Seems that the problem is coming back with piwigo 12.1 and the current versions of batch downloader and the bootstrap darkroom theme :(

I don't know why but at theme "modus" I see the "oldschool" zip icon of the batch downloader. At the bootstrap darkroom theme I see nothing but in the middle of the two icons I got the message "Alle Bilder dieser Auswahl herunterladen" and it works. But I didn't see the icon :(
