### ISSUE TITLE
Logo is overlapping brand-nav

### ISSUE THREAD

**Issue by Tom-Tom1977** [tkuther/piwigo-bootstrap-darkroom#40]
The logo is overlapping the brand-nav. How can I Change the height of the first nav-bar?
Thank you!

**Comment by tkuther** [comment]
You can use custom CSS to raise the min-height, like
```
.navbar-main {
   min-height: 100px;
}
```

**Comment by Tom-Tom1977** [comment]
THANK YOU!!!!!!
