### ISSUE TITLE
New color for bootstrap darkroom, material

### ISSUE THREAD

**Issue by Hotbike** [tkuther/piwigo-bootstrap-darkroom#41]
Is it possible to add the new color "#9f0000" to bootstrap darkroom, color pattern "material" as material color "dark_red"?
Many thanks
Manfred

**Comment by tkuther** [comment]
The colors supported by material bootstrap are listed in https://github.com/FezVrasta/bootstrap-material-design/blob/master/less/_colors.less
If it's an "official" material color, it should be added there, upstream.
