### ISSUE TITLE
Add other social networks.

### ISSUE THREAD

**Issue by zorodimanche** [tkuther/piwigo-bootstrap-darkroom#43]
add reddit and tumblr

**Comment by tkuther** [comment]
The social buttons are from the parent theme, Bootstrap Default. You can add your own as described in the wiki: https://github.com/tkuther/piwigo-bootstrap-darkroom/wiki/Add-custom-share-buttons

**Comment by zorodimanche** [comment]
Ok thanks for your reply i will see.

**Comment by tkuther** [comment]
Also, duplicates #7

**Comment by zorodimanche** [comment]
I have not used piwigo some time since I have to refamilize
