### ISSUE TITLE
Improve the location of the multiple size button

### ISSUE THREAD

**Issue by zorodimanche** [tkuther/piwigo-bootstrap-darkroom#44]
Move the button to the top right corner in the image to enhance the user experience and replace it with a magnifying glass.
![as](https://cloud.githubusercontent.com/assets/25553946/25128243/5546efec-2439-11e7-80ab-ded90feeed08.png)

**Comment by tkuther** [comment]
That's a bit beyond the scope of what Piwigo's template engine can do. It would either require to change the core code that generates the button (not in the theme itself), or modify the result using an awful lot of javascript code to turn that simple menu dropdown entry into a fancy hover menu.

Wontfix, sorry.

**Comment by zorodimanche** [comment]
ok i understand
