### ISSUE TITLE
Add the "Best Rated" photos in order to show the best images

### ISSUE THREAD

**Issue by zorodimanche** [tkuther/piwigo-bootstrap-darkroom#48]

**Comment by tkuther** [comment]
Hm, they are in order in my gallery instance.

**Comment by zorodimanche** [comment]
Here in the special menu
![aaa](https://cloud.githubusercontent.com/assets/25553946/25303977/018a2a4a-275e-11e7-99b0-cfcb33762107.png)

**Comment by tkuther** [comment]
Yeah, but that option exists already, you just need to enable it. Check the demo site.

**Comment by zorodimanche** [comment]
Where that we can activate this option because I searched in the options of the theme there is nothing.

**Comment by tkuther** [comment]
You need to enable rating in Admin -> Configuration -> Options

**Comment by zorodimanche** [comment]
Thank You.
