### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by fabrix95** [tkuther/piwigo-bootstrap-darkroom#49]
Hi,

we use Bootstrap Darkroom with color them Material blue-grey but Search page doesn't work. 

Search bar in home works good. With other themes Search page works but it doesn't work with Bootstrap Darkroom.

http://galleria.pescaraspotters.it/search.php

**Comment by tkuther** [comment]
Wow that's a nasty one.
I can confirm this bug here. Same thing happens in the parent theme Bootstrap Default.

**Comment by tkuther** [comment]
OK. This is caused by the error check in Bootstrap Default about the language switch plugin. Fix on the way...
