### ISSUE TITLE
$derivative is null in mainpage_categories.tpl when category_wells=always

### ISSUE THREAD

**Issue by pommes-frites** [tkuther/piwigo-bootstrap-darkroom#5]
Hi,

I got an error, when when I set category_wells to always and open a mainpage_category page.. The error message was something like "you cannot invoke get_url() on a null object".

I'm new to template coding, but I tried to find the issue. In template/mainpage_categories.tpl line 60 you use $derivative.

data-src="{$derivative->get_url()}"

Since $derivate gets not assigned, when category_wells=always, I assume you want to use $derivative_square, right?

data-src="{$derivative_square->get_url()}"

Thanks
Timo

**Comment by tkuther** [comment]
Your're absolutely correct. Good catch. Thanks!
