### ISSUE TITLE
Add color for social network icons

### ISSUE THREAD

**Issue by zorodimanche** [tkuther/piwigo-bootstrap-darkroom#51]
Improve the visual rendering of the icons of sharing because currently the color when the flyover with the mouse does not mean anything indeed must be added the color of the icons: (https://designpieces.com/2012/12/social-media-colours-hex-and-rgb /

It takes icons with shades of gray and then over the fly with the smile the colors of the icons are displayed.

**Comment by tkuther** [comment]
That's a personal preference. IMHO the picture page is about the picture, and differently colored icons draw your attention off the main element. Feel free to use custom CSS.
