### ISSUE TITLE
Image thumbnail generate by the theme does not respect center of interest

### ISSUE THREAD

**Issue by joshuaavalon** [tkuther/piwigo-bootstrap-darkroom#55]
As title, change the center of interest only regenerate the thumbnail but the center does not change

**Comment by tkuther** [comment]
I can't really reproduce the issue. Works fine here.
Also, the logic comes from the parent theme Bootstrap Default. Please test that one, too, and maybe open a ticket upstream.

**Comment by joshuaavalon** [comment]
It is a Chrome cache problem.
