### ISSUE TITLE
Two information header in image view

### ISSUE THREAD

**Issue by joshuaavalon** [tkuther/piwigo-bootstrap-darkroom#56]
![info](https://cloud.githubusercontent.com/assets/7152420/25435133/a66988e2-2ac1-11e7-9a2d-b09ae13126b7.jpg)

When the `Tabs below the image` is selected, there is two information  header showing. The `Sidebar ` option is fine. May be you forget to remove the title in this option.

**Comment by zorodimanche** [comment]
+1
