### ISSUE TITLE
Bug in the plugin "community" and "Upload 1 menu"

### ISSUE THREAD

**Issue by zorodimanche** [tkuther/piwigo-bootstrap-darkroom#61]
When activating the "Community" plugin and Upload 1 menu allowing the user to add photos the Upload 1 menu plugin creates a link in the menu and this link is not well placed.

**Comment by tkuther** [comment]
What do you mean with not well placed?

**Comment by zorodimanche** [comment]
It is not aligned with the main menu.

**Comment by plegall** [comment]
My fork is somehow broken (absolutely no idea how to fix this #@$grr git repository...), so here the solution for upload1menu: add a file template/menubar_upload.tpl

```
<li class="nav-item">
  <a href="{$U1MURL}" class="nav-link" data-toggle="dropdown" title="{$U1MTITLE}">{$U1MNAME}</a>
</li>
```

I'm going to add on it Piwigo.com, but it would obviously be better for everybody to have in an official release.
