### ISSUE TITLE
HTML errors

### ISSUE THREAD

**Issue by obetz** [tkuther/piwigo-bootstrap-darkroom#65]
in addition to issues inherited from Bootstrap Default (already reported there), Bootstrap Darkroom adds HTML errors.

A severe error is a "!DOCTYPE html.. ..http://www.w3.org/TR/REC-html40/loose.dtd" in the div id="navmenu-contextual". You can see it in pwgdemo.kuther.net/index/category/5-travel

Not so severe:

header.tpl has 'link rel="up"'. "up" seems to be(come) dropped but I consider this not a severe issue as browsers might make use of "up".

picture.tpl h4 is not allowed as child of element dl. As long as it looks good, I don't care.

**Comment by tkuther** [comment]
Which validator are you using? I fully agree it's a mess, but I don't see that one using https://validator.w3.org/nu/?doc=https%3A%2F%2Fpwgdemo.kuther.net%2Findex%2Fcategory%2F5-travel

**Comment by obetz** [comment]
I see it with exactly this validator link, entry number 7: Stray doctype From line 227, column 662; to line 227, column 767

**Comment by tkuther** [comment]
Thanks for reporting! Should be better now.

**Comment by obetz** [comment]
Many thanks for this immediate fix! Now I can publish my site.

I reported minor issues with bootstrapdefault, maybe you want to watch this issue:
https://github.com/Philio/bootstrapdefault/issues/66
