### ISSUE TITLE
js cause no respond with Bootstrap Darkroom

### ISSUE THREAD

**Issue by bd4os** [tkuther/piwigo-bootstrap-darkroom#66]
I like Bootstrap Darkroom theme,but I found Bootstrap Darkroom no respond if the photos quantity more than 1000,firefox report some js cause page slow,it work well if you change to other theme like Bootstrap(without Darkroom),or you delete the most photos and keep a small photo quantity,Bootstrap Darkroom work again.

the demo website like below,it's slowly when you click any photo to detail page.
http://cunsong.com/index.php?/category/2

**Comment by tkuther** [comment]
This is a known issue, especially on servers with low processing power for the database. You can disable Slick carousel and PhotoSwipe which will avoid that heavy query needed for them to work, or tune your database (InnoDB buffer pool, query cache) so it can handle it in a timely manner.

**Comment by bd4os** [comment]
Hello tkuther,thanks for your kind reply,and it work well after I disable Slick carousel and PhotoSwipe,it's really a simple way to solve my issue,this is my first issue at github,I appreciate your professional and help!
