### ISSUE TITLE
Videos in portrait mode are cropped

### ISSUE THREAD

**Issue by maximusVII** [tkuther/piwigo-bootstrap-darkroom#67]
I guess this issue is rather a feature than a "bug".
If I upload a video in portrait mode, the bootstrap theme is cropping the video. It treats the video as it would be in landscape mode (bottom and top of the video are just cut off).

I would prefer a similar behavior as with pictures in landscape mode. The thumbnail is cropped but everything is visible in the detail view.

This issues is related to the bootstrap theme as it is working as expected with other themes.

**Comment by tkuther** [comment]
The video needs to be recoded in true portrait orientation mode. Rotation tags do not work.
See also https://github.com/tkuther/piwigo-bootstrap-darkroom/wiki/Video-support

**Comment by maximusVII** [comment]
Thank you very much for the prompt reply. 
That was my initial thoughts as well but I removed all rotation tags with ffmpeg (-metadata:s:v:0 rotate=0) and the behavior is the same. Maybe my ffmpeg command does not solve the rotation issue.
Any ideas?

**Comment by tkuther** [comment]
I posted my script to the wiki article. Basically it's
```ffmpeg -i $INPUT -map_metadata 0 -c:v libx264 -c:a aac $OUTPUT```

**Comment by maximusVII** [comment]
If just tested it and unfortunately it is still not working (the movie is rotated correctly but still zoomed to match the width of the player and the top and the bottom are cropped).
I use the following ffmpeg command to rotate the image and to remove the rotation metadata:
ffmpeg -i $INPUT -vf 'transpose=1' -map_metadata 0 -c:v libx264 -c:a aac --strict -2 $OUTPUT
I even tried your command in addition but the behavior is still the same.

Any idea?

**Comment by tkuther** [comment]
You say it works in other themes. Does that mean you are using piwigo-videojs?

**Comment by maximusVII** [comment]
That was a mistake of mine - I just see a picture if I use another theme (as piwigo-videojs is not installed).

I've tested a few things in the meantime and made some screenshots.
Don't get confused, I downloaded the following sample video (http://www.sample-videos.com/) and just rotated it by 90 degrees to get a movie in portrait mode (its no longer correctly rotated but in portrait mode).

Thumbnail view with clear theme
![clear_tn](https://cloud.githubusercontent.com/assets/22932853/26725100/1f6f9b76-479d-11e7-8b67-11decaf67e15.jpeg)

Thumbnail view with bootstrap darkroom
![darkroom_tn](https://cloud.githubusercontent.com/assets/22932853/26725106/2b2b4bf4-479d-11e7-8460-5ccb546f8f14.jpeg)

Details view with bootstrap darkroom (movie is cropped and zoomed to fit the width)
![darkroom_detail](https://cloud.githubusercontent.com/assets/22932853/26725107/2ef7f0f2-479d-11e7-9d4f-3dab95f58aec.jpeg)

I then downloaded and activated piwigo-videojs and configured it to use the browser to play the movie and suddenly, the movie is no longer cropped but too high. 
![bootstrap_play](https://cloud.githubusercontent.com/assets/22932853/26725411/b7e49d56-479e-11e7-8d56-b1ecfcb49500.jpeg)

**Comment by tkuther** [comment]
Ok, it's broken on the picture detail page here too. I was just looking at PhotoSwipe.

Responsive embed causes the cropping, but even removing that causes a mess with fullscreen mode scaling. I'll see if a fix is possible.

**Comment by tkuther** [comment]
Err, could you please test a possible fix?

In themes.css remove/comment out the line saying
```
video[poster] { object-fit: cover; }
```
It does look a bit awkward on the picture page baucause video controls and dropshadows still are 16 to 9, but first I need to know if that damn video[poster] CSS setting really is the main cause for all that mess (can't hardly believe it)

**Comment by maximusVII** [comment]
Thanks a lot for your reply.

I removed the line and the video is now showing up in portrait mode (just the video control and shadows are still 16:9).

**Comment by tkuther** [comment]
I have added some workarounds for the controls, too. If you see any side effects from removing that CSS property, let me know. All looks OK here, no idea why I added it in the first place o.O

Thanks for testing (and reporting).
