### ISSUE TITLE
"User tags" extension compatibility

### ISSUE THREAD

**Issue by bydesignparis** [tkuther/piwigo-bootstrap-darkroom#69]
Hi, i'm using both bootstrap-darkroom and the extension "User tags". To make them work together, i had to fix 2 lines in bootstrap-darkroom picture.tpl. Thanks for integrating this fix in your next version.

Regards
bruno

```
line 210: <tr id="Tags" class="imageInfo"> replaced by <tr>
line 213: created <div id="Tags" class="imageInfo">
line 215: close the div created
```

![image](https://user-images.githubusercontent.com/19536902/27026125-081b1bc2-4f5d-11e7-97ce-09ea7c2dceb7.png)

**Comment by tkuther** [comment]
Fixed in 45af83d
