### ISSUE TITLE
Add Diaspora social media share Button.

### ISSUE THREAD

**Issue by inkhey** [tkuther/piwigo-bootstrap-darkroom#7]
Sharing buttons are now available only for proprietary and centralised social media, be able to have same kind of buttons for alternatives such as diaspora would be a nice improvement.

**Comment by tkuther** [comment]
The social buttons come from the parent theme, Bootstrap Darkroom. I could add extra buttons here, but a) the config would get confusing, and b) sharing to diaspora in that case requires more than just a simple API-URL call, and therefore goes way beyond the scope of a simple social button. It would require a separate plugin.

Closing as wontfix.

**Comment by tkuther** [comment]
See https://github.com/tkuther/piwigo-bootstrap-darkroom/wiki/Add-custom-share-buttons
