### ISSUE TITLE
Last update pictures info problem

### ISSUE THREAD

**Issue by fabrix95** [tkuther/piwigo-bootstrap-darkroom#70]
Hi,

from last update I see AddInfo plugin on "Tags" and Author doesn't appear.

![cattura](https://user-images.githubusercontent.com/27883759/27100006-f5b3aa64-507c-11e7-8e4f-4fa3350ed496.PNG)

**Comment by tkuther** [comment]
Yeah it needs special treatment, just like openstreetmap in https://github.com/tkuther/piwigo-bootstrap-darkroom/blob/master/template/_plugin_fixes_js.tpl

But given AddInfo is deprecated, I won't support it.
