### ISSUE TITLE
Author doens't appear

### ISSUE THREAD

**Issue by fabrix95** [tkuther/piwigo-bootstrap-darkroom#71]
Hi,

I disabled Addinfo but Author doesn't appear.
![cattura](https://user-images.githubusercontent.com/27883759/27102007-05eed956-5084-11e7-803e-77c42880f2c8.PNG)

**Comment by tkuther** [comment]
Fixed in 3b55759d2f4235e36b7c4da17bad718bc7e54be2 and already released in 1.5.12. Thanks!
