### ISSUE TITLE
Manage Properties Photos?

### ISSUE THREAD

**Issue by fabrix95** [tkuther/piwigo-bootstrap-darkroom#72]
Hi guys,

sorry if I seem insistent but I'm only trying to unerstand how to set my gallery :)

Is bootstrap darkroom compatible with 'Manage Properties Photos' plugin? 
Because I set it but info doesn't appear on image properties. 
If not, are any chance to make it compatible? If not, what do you suggest to add 'location' at the images?

Thanks in advance

**Comment by tkuther** [comment]
Unfortunately not. It tries to replace the full info with preg_replace and expects a different DOM structure here. Doesn't support templates either.

**Comment by tkuther** [comment]
PS: it should work if using "Sidebar" instead of "Tabs below the image" in theme config, though.

**Comment by fabrix95** [comment]
Even with sidebar doesn't work

**Comment by tkuther** [comment]
This is fixed in upcoming 2.x, but only for the sidebar view.
