### ISSUE TITLE
update with error?

### ISSUE THREAD

**Issue by rosimittermeier** [tkuther/piwigo-bootstrap-darkroom#73]
today I updated the theme. now the site ist broken:

Warning: Cannot modify header information - headers already sent by (output started at /home/www/piwigo/themes/bootstrap_darkroom/language/de_DE/theme.lang.php:84) in /home/www/piwigo/include/functions.inc.php on line 847

Warning: Cannot modify header information - headers already sent by (output started at /home/www/piwigo/themes/bootstrap_darkroom/language/de_DE/theme.lang.php:84) in /home/www/piwigo/include/functions.inc.php on line 848

Warning: Cannot modify header information - headers already sent by (output started at /home/www/piwigo/themes/bootstrap_darkroom/language/de_DE/theme.lang.php:84) in /home/www/piwigo/include/functions.inc.php on line 849

**Comment by tkuther** [comment]
Does removing the last 2 lines in language/de_DE/theme.lang.php fix this?
```?>

```
(the very last line is empty, actually)

**Comment by rosimittermeier** [comment]
YES!!! Tanks!   14.06.2017, 12:43, "Thomas Kuther" <notifications@github.com>:Does removing the last 2 lines in language/de_DE/theme.lang.php fix this?
(the very last line is empty, actually)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by tkuther** [comment]
Fixed in 843afdd
