### ISSUE TITLE
Menu truncated when not logged in and index page is empty

### ISSUE THREAD

**Issue by dregad** [tkuther/piwigo-bootstrap-darkroom#75]
When accessing the menus, the bottom part of each one is truncated and a vertical scroll bar is displayed (see screenshots). 
![screenshot-20170619-1530](https://user-images.githubusercontent.com/449891/27287531-4f31142e-5504-11e7-9399-34d59e5afc3b.png)
![screenshot-20170619-1531](https://user-images.githubusercontent.com/449891/27287580-7515f5b0-5504-11e7-9ebc-800d1ca76529.png)

The problem disappears once user is logged in
![screenshot-20170619-1533](https://user-images.githubusercontent.com/449891/27287670-d01c59ea-5504-11e7-81f8-bacf9796383e.png)

Other than that, thanks for a very nice theme !

**Comment by tkuther** [comment]
From the screenshot it seems the page is empty. So, the page body's height is smaller than the menu would require. A workaround could be to set a min-height on the body - could you try that custom CSS?

```
body {
   min-height: 250px;
}
```
Maybe play with the value a bit until it fits.

**Comment by dregad** [comment]
> From the screenshot it seems the page is empty

Correct

> could you try that custom CSS

That does not resolve the problem; if I put in a very large value (e.g. 2000px), a second scrollbar spanning the whole browser window's height is displayed to the right of the menu's small one, which remains the same as per my earlier screenshots.

Following the suggested logic, I could fix it by adding `min-height: 100px;` to the _div.container_
![screenshot-20170619-1625](https://user-images.githubusercontent.com/449891/27289957-06383d76-550c-11e7-8e6d-283ea2b54294.png)

**Comment by tkuther** [comment]
Okay, thanks. Does this one work, too?
```
#content {
  min-height: 100px;
}
```

**Comment by dregad** [comment]
@tkuther Yes, the menus display fine with this one too.

**Comment by tkuther** [comment]
Okay, so I'll add that one as a default. Thanks for testing!

**Comment by dregad** [comment]
@tkuther many thanks for the fix and the fast turnaround time !
