### ISSUE TITLE
Incomplete support for "User Collections" plugin

### ISSUE THREAD

**Issue by dregad** [tkuther/piwigo-bootstrap-darkroom#76]
The [support matrix](https://github.com/tkuther/piwigo-bootstrap-darkroom/wiki/Plugin-Support-Matrix) mentions that _User Collections_ plugin is supported, yet it does not seem to be possible to individually add pictures to a collection from the album's list view (or if it is, I didn't find how to do it).

Compare with the _dark_ theme, where hovering the mouse over a thumnail displays an _Add to collection_ option
![screenshot-20170619-1549](https://user-images.githubusercontent.com/449891/27288470-1acc3ce2-5507-11e7-931c-570e61b33d3e.png)

**Comment by tkuther** [comment]
Currently the mouse hover works with gdThumb/gThumb+ only, true.

**Comment by dregad** [comment]
I'm not sure how to interpret your answer - is this something that can (and will eventually) be fixed in the theme ? Or do I need to do something on the _User Collections_ side ? 

This is the only issue that makes me hesitate to set bootstrap darkroom as default theme, and would love to make the switch.

**Comment by tkuther** [comment]
The default grid uses a completely different HTML structure than the preg_replace voodoo in the plugin expects. So I cannot support it.

But as said, it does work fine with the GThumb+ plugin.

**Comment by tkuther** [comment]
Great!

Typo corrected, thanks.
