### ISSUE TITLE
User collection plugin display bug

### ISSUE THREAD

**Issue by bydesignparis** [tkuther/piwigo-bootstrap-darkroom#77]
Alert boxes are not displayed correctly within the share-form:

![image](https://user-images.githubusercontent.com/19536902/27296160-144a7b68-5520-11e7-8e9c-cef2cf40dbb5.png)

To fix it, modify piwigo/themes/bootstrapdefault/template/info_error.tpl and replace the "container" class by a "container-fluid" class.
![image](https://user-images.githubusercontent.com/19536902/27296269-7986379c-5520-11e7-8276-2275301ecc55.png)

**Comment by tkuther** [comment]
Thanks! I'll include it in bootstrap darkroom for now. But please open an issue for it in bootstrap default, too.

**Comment by bydesignparis** [comment]
> But please open an issue for it in bootstrap default, too.
Done. THanks for the fix
