### ISSUE TITLE
Enhancement request: show count of comments in picture page

### ISSUE THREAD

**Issue by bydesignparis** [tkuther/piwigo-bootstrap-darkroom#79]
To enhance UX, it might be useful to show viewers whether a picture has comments with a bootstrap badge on the tab title:

![image](https://user-images.githubusercontent.com/19536902/27324265-ee9d3c86-55a4-11e7-9c4e-9fbb6dfc94f6.png)

This badge is added into the page by the code below:
```javascript
$(document).ready(function () {
  var badge,
    tab_comments = $('a[href="#tab_comments"]');
  if (tab_comments.length) {
    if ($(".comment").length) {
      badge = '&nbsp;<span class="badge">' + $(".comment").length + '</span>';
      tab_comments.append(badge);
    }
  }
 });
```

**Comment by tkuther** [comment]
Great idea! I'll add it.
