### ISSUE TITLE
Can't save photos to camera roll (IOS)

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#80]
Hi Thomas, not sure if this is a bug or a feature, but I just noticed that if I'm browsing a category (www.peu.net) and want to save any image to the camera roll it can't be done like with any other website. There is no way, the only action allowed is to move to the next or previous image. Thanks!

**Comment by tkuther** [comment]
Hi Pablo,

on the picture detail page a long press on the picture brings up the "save picture" option, or you can use the download button -> iOS share option -> save image.

In the PhotoSwipe slideshow the long press doesn't work, use share button -> download image (opens new browser tab) -> iOS share option -> save image
