### ISSUE TITLE
Random photo problem

### ISSUE THREAD

**Issue by fabrix95** [tkuther/piwigo-bootstrap-darkroom#81]
Hi guys,

'Random photo' show me only album instead of photos. 

http://www.galleria.pescaraspotters.it/random.php

**Comment by tkuther** [comment]
Hi,

hm, that's weird. I cannot reproduce it in my own gallery or on the darkroom demo.

**Comment by fabrix95** [comment]
So maybe it's my problem with Piwigo :(
