### ISSUE TITLE
Hide filename from meta description

### ISSUE THREAD

**Issue by fabrix95** [tkuther/piwigo-bootstrap-darkroom#82]
Hi,

are there any way to hide the filename from content of meta "description"?

`<meta name="description" content="... - _filename_.jpg">`

**Comment by tkuther** [comment]
You would need to edit template/header.tpl and remove the `{if isset($INFO_FILE} - {$INFO_FILE}{/if}`

I guess Icould remove that by default, because the use of having the filename in there is questionalble.

**Comment by fabrix95** [comment]
Thank you!

I replaced with `{$INFO_AUTHOR}{/if}` that can be more useful.

**Comment by fabrix95** [comment]
Are there any chance to remove filename even from `alt` attribute of img?

**Comment by You85** [comment]
+1

It might be more judicious in terms of referencing to add the description of the photo.

**Comment by tkuther** [comment]
While I totally agree with you, I still won't make changes to the theme in that case.
The alt attribute is derived from the ALT_IMG variable set in picture.php, see https://github.com/Piwigo/Piwigo/blob/master/picture.php#L212.

Sure, you could edit the theme template to use something else than $ALT_IMG, but I think it's the wrong place to do it.
