### ISSUE TITLE
HTML errors

### ISSUE THREAD

**Issue by obetz** [tkuther/piwigo-bootstrap-darkroom#83]
Currently, the alt= and title= are not preceded by a (needed) space. The template engine seems to concatenate subsequent lines without whitespace.

Since https://github.com/Philio/bootstrapdefault/issues/66 is still not fixed in bootstrapdefault, I suggest to apply a fix to bootstrap darkroom, mainpage_categories.tpl (lines 28..30) and thumbnails.tpl (lines 44..46).

I simply combined the three lines into one to get the space between the tags. Maybe there is a more elegant way.

**Comment by tkuther** [comment]
Done! Thanks.
