### ISSUE TITLE
Improve the search bar by replacing it with a magnifying glass

### ISSUE THREAD

**Issue by You85** [tkuther/piwigo-bootstrap-darkroom#84]
Before: 
![zhsuzi](https://user-images.githubusercontent.com/30325749/28433637-a6359c40-6d8c-11e7-9c87-181f41e97775.png)

After:
![hjjkjhj](https://user-images.githubusercontent.com/30325749/28433643-abff59f4-6d8c-11e7-8009-3e9c29c0ebec.png)

Check this link to see the example on the site : https://bootsnipp.com/snippets/featured/even-simpler-navbar-search

**Comment by tkuther** [comment]
Pretty cool idea!

**Comment by You85** [comment]
Thank You

**Comment by GuillaumeCyriaque** [comment]
Hi,
Good idea. Works with some simple CSS:
```
#quicksearch input[type="text"] {
  background: url(link_to_searchicon) no-repeat 6px;
  width: 20px !important;
  border: none !important;
  -webkit-box-shadow: none !important;
  -moz-box-shadow: none !important;
  -webkit-transition: all 0.7s ease 0s;
  -moz-transition: all 0.7s ease 0s;
  -o-transition: all 0.7s ease 0s;
  transition: all 0.7s ease 0s;
}

#quicksearch input[type="text"]:focus {
  background: none;
  width: 150px !important;
}
```
NB: I used a 12x12px png icon.

**Comment by You85** [comment]
Like this : http://fontawesome.io/icon/search/

**Comment by GuillaumeCyriaque** [comment]
Like this ?
```
#quicksearch {
  position: relative;
}
#quicksearch:before {
  font-family: "FontAwesome";
  font-size: 14px;
  content: "\f002";
  position: absolute;
  top: 8px;
}
#quicksearch input {
  text-indent: 10px;
}

#quicksearch input[type="text"] {
  background: 14px;
  width: 14px !important;
  border: none !important;
  -webkit-box-shadow: none !important;
  -moz-box-shadow: none !important;
  -webkit-transition: all 0.7s ease 0s;
  -moz-transition: all 0.7s ease 0s;
  -o-transition: all 0.7s ease 0s;
  transition: all 0.7s ease 0s;
}
#quicksearch input[type="text"]:focus {
  background: none;
  width: 150px !important;
}
 ```
[http://guillaumecyriaque.be/](url)

**Comment by tkuther** [comment]
@GuillaumeCyriaque nice one!

Do you agree that this should be done only for the desktop view? When the navbar is collapsed (i.e. on mobile phones) that behaviour is a bit awkward, IMHO.

**Comment by GuillaumeCyriaque** [comment]
@tkuther yes, as you want. No problem for me, it was just an example with simple css only ;-)
Nice on desktop or tablet but not on phones.

**Comment by tkuther** [comment]
Will be in next release. Thanks guys for idea and implementation!

**Comment by GuillaumeCyriaque** [comment]
Seen but search icon offset.
