### ISSUE TITLE
The title of the gallery is smaller in Microsoft edge

### ISSUE THREAD

**Issue by You85** [tkuther/piwigo-bootstrap-darkroom#85]
![iedge](https://user-images.githubusercontent.com/30325749/28502491-c46a2bc2-6ff3-11e7-8d81-b7f1bd3226f5.png)
Latest version of Microsoft

While in the latest version of chrome the title is displayed correctly

**Comment by tkuther** [comment]
Hm, I cannot reproduce it here in Edge. Looks OK on pwgdemo.kuther.net.
