### ISSUE TITLE
Enhance the user profile page ( profile.php )

### ISSUE THREAD

**Issue by You85** [tkuther/piwigo-bootstrap-darkroom#87]
Improve the display of the user profile page. In fact, currently it must go down vertically to modify the parameters it would be interresant to add a horizontal menu with preferences ...
Like this : https://bootsnipp.com/snippets/featured/people-card-with-tabs

**Comment by tkuther** [comment]
This would have a negative effect on mobile UX, IMHO. I agree that it could need some better formatting/styling but splitting it into tabs would make things even worse.
