### ISSUE TITLE
Map icon not shown with RV Maps & Earth plugin

### ISSUE THREAD

**Issue by ScottFerg56** [tkuther/piwigo-bootstrap-darkroom#88]
This could be a problem with Bootstrap or RV Maps & Earth:
On the picture page the map icon does not appear, but divides the navbar into two lines.

The map icon does not come in as an LI element and does not use the same CSS class structure as the other icons.

There's more info and illustrations in a Piwigo forum discussion at:
http://piwigo.org/forum/viewtopic.php?id=27910

**Comment by tkuther** [comment]
This is fixed in https://github.com/tkuther/piwigo-bootstrap-darkroom/commit/2a805a63a576c78bdf59bad8f40efe54109717f5
