### ISSUE TITLE
Replace the image magnification icon

### ISSUE THREAD

**Issue by You85** [tkuther/piwigo-bootstrap-darkroom#89]
![1](https://user-images.githubusercontent.com/30325749/28748057-d110dc90-74ad-11e7-8f2d-1c271b80411e.png)

By this one : https://www.iconfinder.com/icons/184367/arrows_enlarge_full_screen_fullscreen_photo_photography_zoom_icon#size=128

**Comment by tkuther** [comment]
That's a commercial icon, no redistribution, etc. Not possible. We use FontAwesome in the theme.

**Comment by You85** [comment]
Yes it is commercial but I found a free and open source icon that illustrates the enlargement of an image:
http://fontawesome.io/icon/arrows-alt/
