### ISSUE TITLE
Wrong photo while jumping directly to PhotoSwipe slideshow with User Collections plugin

### ISSUE THREAD

**Issue by rools32** [tkuther/piwigo-bootstrap-darkroom#9]
When I enable Link thumbnail to PhotoSwipe slideshow, I can go from an thunmbnail in my album directly to PhotoSwipe slideshow. But the problem is I have the wrong photo opened. The index of the opened photo is twice as it should be.
My versions are:
  - Piwigo 2.8.2
  - Bootstrap Darkroom 1.4.9

Thanks.

**Comment by tkuther** [comment]
Hmm, I found a bug which has to do with number of images per page and pagination.

If the image is on the second, third etc page, it would open the image on the first page. Say you have images per page set to 50, and go to 2nd page in the album and click the first image, PhotoSwipe would open with image index 0 from first page.

Is this the issue you are seeing?

This is fixed in https://github.com/tkuther/piwigo-bootstrap-darkroom/commit/9a94e020aef87cdd02479ed9e9c797749aa71e4e now.

**Comment by rools32** [comment]
Unfortunately, it is not this bug. I don't see any difference when the image is in another page (which is loaded automatically while I am scrolling).

I checked the plugins and saw that the bug is only present when **GThumb+** is enabled.

When I replace **GThumb+** by **gdThumb** and I don't have the bug anymore. But when **Link thumbnail to PhotoSwipe slideshow** is on with **gdThumb**, the plugin **Image Preview** isn't working anymore.

**Comment by tkuther** [comment]
Interesting. I use Gthumb+ myself and don't see this bug at all. I had to disable it to find the issue above. I suspect this is an issue with the Gthumb+/Image Preview combination.

Can you confirm it's working with Gthumb+ if Image Preview is disabled?

**Comment by rools32** [comment]
Even with Image Preview disabled, the bug is still there.

**Comment by tkuther** [comment]
Could you show the HTML code of one single image element, please?

Here it looks like:
```
<li class="gthumb" style="height: 188px; width: 141px;">
    <span class="thumbLegend">
      <span class="thumbName">
        OLY01695
      </span>
          </span>
  <a href="javascript:;" data-index="17" style="clip: rect(6px 146px 194px 5px); top: -6px; left: -5px;">
    <img class="thumbnail" src="../../i/upload/2016/08/08/20160808203728-0a04c5e6-cu_s9999x200.jpg" alt="OLY01695" title="OLY01695 (2 besuche) OLYMPUS DIGITAL CAMERA" width="150" height="200">
  </a>
</li>
```
Maybe you have a second anchor link in there which could indeed mess up the data-index logic.

**Comment by rools32** [comment]
I forgot to mention I have the plugin **User Collections**.
My HTML is like that:
`<li class="gthumb">
<a class="addCollection" data-id="31" data-cols="[]" rel="nofollow">Ajouter à une collection&nbsp;<img src="./plugins/UserCollections/template/resources/image_add.png" alt="[+]"></a>
    <span class="thumbLegend">
      <span class="thumbName">
        20160712 085344 Anaëlle
      </span>
          </span>
  <a href="picture.php?/31/category/5"  imgsrc="_data/i/upload/2016/08/30/20160830085317-e91c158f-cu_s600.jpg" data-tittle="20160712 085344">
    <img class="thumbnail" src="_data/i/upload/2016/08/30/20160830085317-e91c158f-cu_s9999x300.jpg" alt="20160712 085344" title="20160712 085344" width="450" height="300">
  </a>
</li>`

**Comment by rools32** [comment]
I forgot to mention I have the plugin **User Collections**.

My HTML is like that:

```html
<li class="gthumb">
<a class="addCollection" data-id="31" data-cols="[]" rel="nofollow">Ajouter à une collection&nbsp;<img src="./plugins/UserCollections/template/resources/image_add.png" alt="[+]"></a>
    <span class="thumbLegend">
      <span class="thumbName">
        20160712 085344
      </span>
          </span>
  <a href="picture.php?/31/category/5"  imgsrc="_data/i/upload/2016/08/30/20160830085317-e91c158f-cu_s600.jpg" data-tittle="20160712 085344">
    <img class="thumbnail" src="_data/i/upload/2016/08/30/20160830085317-e91c158f-cu_s9999x300.jpg" alt="20160712 085344" title="20160712 085344" width="450" height="300">
  </a>
</li>
```

**Comment by tkuther** [comment]
Could you try editing template/index.tpl in the theme folder, line 291
Replace
```
function setupPhotoSwipe() {
   $('#thumbnails').find('a').each(function(_index) {
```
with
```
function setupPhotoSwipe() {
   $('#thumbnails').find("a:not('.addCollection')").each(function(_index) {
```

**Comment by rools32** [comment]
Yes, it works.

**Comment by tkuther** [comment]
Cool. The fix will be in next version.
