### ISSUE TITLE
Fatal error: Uncaught --> Smarty: Missing template name <-- 

### ISSUE THREAD

**Issue by Romtom03** [tkuther/piwigo-bootstrap-darkroom#90]
After updating the template to 1.5.18 I received the following Error while trying to access the gallery 

`Fatal error: Uncaught --> Smarty: Missing template name <-- thrown in /piwigo/include/smarty/libs/sysplugins/smarty_template_source.php on line 157`

I tracked it down, to be some problem when the plugin **Advanced Menu Manager** 3.2.12 is running.

Don't know whether the template or the plugin needs some fixing. Hope you know better. ;-)

**Comment by tkuther** [comment]
It _could_ be the theme in combination with plugin, not sure though. There are similar errors notes on the forums related to AMM. But given Adavanced Menu Manager is totally unsupported in the theme (or the theme in the plugin) please try without AMM and if that works the theme is fine. 😎
