### ISSUE TITLE
Fatal error: Uncaught --> Smarty: Missing template name

### ISSUE THREAD

**Issue by loopway** [tkuther/piwigo-bootstrap-darkroom#91]
After updating the template to 1.5.18 I received the following Error while trying to access the gallery

Fatal error: Uncaught --> Smarty: Missing template name <-- thrown in /piwigo/include/smarty/libs/sysplugins/smarty_template_source.php on line 157

Unlike @Romtom03 I have no "Advanced Menu Manager" or any other plugin installed.

Downgraded to version 1.5.16 and the issue disappeared again. 

Environment:

- Piwigo 2.9.1
- Operating system: Linux
- PHP: 7.0.21 (Show info) [2017-07-31 15:41:44]
- MySQL: 5.6.33-cll-lve [2017-07-31 15:41:44]
- Graphics Library: ImageMagick 6.9.4-10

**Comment by tkuther** [comment]
Ok, so it's the theme. It happens somewhere around the new menubar.tpl I guess, but I'd need a way to reproduce the issue. Doesn't happen on any of my 3 Piwigo installations..

**Comment by loopway** [comment]
I can't provide you access to the installation. But let me know if I can collect some logs or debug information.

**Comment by GuillaumeCyriaque** [comment]
Hi Thomas,
Same problem for me : 
If I desactivate Advanced Menu Manager plugin, it's OK... in appearence !
If I uncheck "mbSpecials" in the (normal) menu options, the error comes back. Not for the other options.
BUT, if I reactivate Advanced Menu Manager plugin and displays mbSpecials, fatal error too.
I hope this will be helpful.

**Comment by tkuther** [comment]
@GuillaumeCyriaque that's helpful, indeed. Thanks!

mbSpecials is indeed sort of hard-included now. There should be a test if it's activated at all.
I'll come up with a fixed version, soon.
