### ISSUE TITLE
No automatic PhotoSwipe Slideshow

### ISSUE THREAD

**Issue by haniibrahim** [tkuther/piwigo-bootstrap-darkroom#93]
I use the current Piwigo and bootstrap-darkroom version. I set up in _Extra Settings:_

Thumbnail page display:
     Link thumbnail to:  `PhotoSwipe Slideshow (Mobile Device only)`

But even on mobile devices  it shows the _Picture Detail Page_ and not the PhotoSwipe Slideshow directly. Even when I choose `PhotoSwipe Slideshow` I got the same result on all devices => _Picture Detail Page_ instead of _PhotoSwipe_.

I can remember that this feature works in former Piwigo or Bootstrap-darkroom theme versions properly. I have noticed this problem for quite a long time since a couple Piwigo/Theme updates,

Is this a bug?

Thanks,

Hani

**My Environment:**
Piwigo 2.9.1
Linux
PHP: 5.5.38-nmm2
MySQL: 5.6.33-nmm1-log
ImageMagick 6.7.7-10

**Comment by haniibrahim** [comment]
Find a workarount by installing the plugin: **GThumb+**

**Comment by tkuther** [comment]
This was a rather stupid bug that is now fixed in 1.5.20. I didn't see it because I'm using Gthumb+ myself on all sites.

Thanks for reporting @haniibrahim

**Comment by haniibrahim** [comment]
Thanks for taking care. Works now. Gorgeous theme. Thanks for providing.
