### ISSUE TITLE
Bootstrap hover effects on picture/and album picture

### ISSUE THREAD

**Issue by You85** [tkuther/piwigo-bootstrap-darkroom#94]
Subtle hover effects will make your website more beautiful and interactive.
Image Hover Effect Using Bootstrap CSS3 : https://mdbootstrap.com/css/hover-effects/

**Comment by tkuther** [comment]
On mobile, there is no hover. I'd like to avoid desktop-only bling bling in the theme because one of its main aspects is mobile-readyness.

**Comment by tkuther** [comment]
In Darkroom 2.x, the ripple effect is applied to thumbnails when using any of the material-* styles
