### ISSUE TITLE
Feature Request: Hoverable Dropdown

### ISSUE THREAD

**Issue by You85** [tkuther/piwigo-bootstrap-darkroom#95]
Hi, It would be interesting to improve the user experience by displaying the submenu at the cursor.
Like this : http://www.jquery-az.com/boots/demo.php?ex=37.0_3
Thanks You

**Comment by tkuther** [comment]
Keep in mind that bootstrap is mobile-first. There is no cursor.. 

I'd prefer to keep the menu simple. Maybe in a subtheme.
