### ISSUE TITLE
Improved theme: add a contact page

### ISSUE THREAD

**Issue by You85** [tkuther/piwigo-bootstrap-darkroom#97]
Like this : https://bootsnipp.com/snippets/featured/simplest-contact-form

**Comment by GuillaumeCyriaque** [comment]
Already exists : http://fr.piwigo.org/ext/extension_view.php?eid=304

**Comment by You85** [comment]
Yes I already saw this plugin but the rendering is not pretty. It lacks colors and there is no design.

**Comment by tkuther** [comment]
Then the plugin should be styled to fit the theme.
