### ISSUE TITLE
Eliminate JavaScript and CSS codes that block the display of content above the waterline

### ISSUE THREAD

**Issue by You85** [tkuther/piwigo-bootstrap-darkroom#98]
Optimize the display of CSS styles for the following URLs:
https://pwgdemo.kuther.net/_data/combined/192krwq.css
https://pwgdemo.kuther.net/…ap_darkroom/components/pTSans/pTSans.css

Test with Google page speed : https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpwgdemo.kuther.net%2F&tab=desktop

**Comment by tkuther** [comment]
The theme is tuned for pagespeed with best effort, but only to the point where things stop making sense.
