### ISSUE TITLE
Menus too long for page

### ISSUE THREAD

**Issue by SciFiKriss** [tkuther/piwigo-bootstrap-darkroom#99]
Hi guys

I am using the material theme and find that the menu is too long for the screen... whereas the bootswatch ones are ok.

Thanks in advance

Kriss :)
![untitled2](https://user-images.githubusercontent.com/31061838/29352923-6c6970fc-8260-11e7-85b0-7a4a72b18f2d.jpg)

**Comment by tkuther** [comment]
That's a bit unfortunate, I'd even call it a style bug, sort of. But the menu scrolls together with the rest of the page, so functionality is still there, right?

**Comment by SciFiKriss** [comment]
It is yes but wondering if it could be shortened... or is that something that someone else would do?

Kriss :)

**Comment by tkuther** [comment]
You could use custom CSS, like
```.navbar .dropdown-menu li>a,
.navbar.navbar-default .dropdown-menu li>a {
￼    font-size: 16px;
￼    padding: 5px 16px;
}
```
Default padding: 13px 16px;
So, play with the first value (top/bottom).

**Comment by SciFiKriss** [comment]
Thanks!

**Comment by SciFiKriss** [comment]
Woohoo! thanks!

**Comment by tkuther** [comment]
This should be improved in upcoming 2.0.6

**Comment by SciFiKriss** [comment]
I had noticed something happen on an update :)

Kriss :)

Kriss :)
Krissmania <http://krissharmsworth.rocks/blog/>
